### PR TITLE
Add some demo code for county FIPS

### PR DESCRIPTION
**Pull request by karldw**
This PR starts to address #338. It assigns FIPS based on state and county names, using an existing EIA datapackage. Feel free to make changes, or just copy out anything you find useful!

(Another step, which I haven't done, would be checking that these counties are consistent with the declared lat/lon.)

### CODE REVIEW

**Comment by karldw** [comment]
Notes on some of the more unusual name corrections:
- The plant that lists its county as Plaquemines, NH, says its city is [Groveton](https://en.wikipedia.org/wiki/Groveton%2C_New_Hampshire), so I assigned Groveton's county, Coos.
- [Kusilvak](https://en.wikipedia.org/wiki/Kusilvak_Census_Area,_Alaska) is the new name for Wade Hampton

**Comment by zaneselvans** [comment]
Hey @karldw, okay this is pulling FIPS codes from the authoritative US Census source, and then attempting to merge them in based on state & county names, which ends up requiring a few spelling fixes. So this is something we'd want to integrate into the EIA ETL process when it's working.

How stable do you think that Census spreadsheet is? Should we pull that data into PUDL (or maybe just into the repository as a CSV)?  There's also [this EPA REST API](https://www.epa.gov/frs/frs-rest-services) for finding facility IDs, which I think @gschivley mentioned at some point, and which includes the FIPS code in its outputs.  Not sure if that would be painfully slow to do for all of them in bulk.

**Comment by karldw** [comment]
I had forgotten about the REST API. I don't think it would be that bad to look up every plant, and those queries can be run in parallel. That said, if this is going to be part of each ETL, it might be good to do some caching or make a pre-compiled list. 

Here's a function that looks up details for one plant: https://github.com/catalyst-cooperative/pudl/issues/178#issuecomment-460005289

**Comment by zaneselvans** [comment]
Hey @karldw we're integrating the FIPS codes as part of our work on FERC 714 planning area integration. So they should be available in both the EIA 860 and EIA 861 tables soon.

**Pull request closed without merging**
