### PR TITLE
Quickstart

### PR DESCRIPTION
**Pull request by gschivley**
Propose a quickstart section a the top of README that points users to the getting started files. No similar pointer exists right now.

### CODE REVIEW

**Comment by zaneselvans** [comment]
Hey @gschivley thank you for getting involved! We haven't worked with python environments yet, but I see in your data science short course you're a big fan of using them on a per-project basis. The requirements.txt file has thus far been a list of minimum versions required for the whole thing to function, rather than a suite of particular specified versions.  As such it hasn't been updated very assiduously... and may well be out of date. What's the norm with environments? Do they typically march forward with the newest available package versions, unless there's a reason/need to hold one back? Is there a good way to automate updating the listed versions based on currently installed versions once you've verified that they work?

**Comment by zaneselvans** [comment]
And the quickstart is obviously a good idea. We need to update the whole readme, honestly.

**Comment by karldw** [comment]
@gschivley and @zaneselvans, maybe also worth highlighting the conda [requirements file](https://github.com/catalyst-cooperative/pudl/blob/master/docs/requirements_conda.txt). The more recent editions of the setup instructions pull from there. I meant to set up pinning too, so a `conda update --all` won't break things, but haven't gotten around to it. (See #150)

**Comment by zaneselvans** [comment]
I've been reading a bit out conda environments last night and this morning, and am trying to pull together a working `environment.yml` that includes just the non-standard packages we need to make it work.  In the process (surprise!) I seem to have broken my local build, so I'm debugging that at the moment.

Should we pin those non-standard packages to a particular minor version, and only upgrade them after testing within a new environment (e.g. after a major Anaconda release)?

**Comment by gschivley** [comment]
Missed this thread. I used conda environments from the start and have stuck with them ever since. Most of my projects have been fairly short term so I haven't worried about pinning versions.

[I created an `environment.yml`](https://github.com/gschivley/pudl/blob/master/environment.yml) from your `requirements.txt`. Then almost included it in this PR...

**Pull request merged**
