### PR TITLE
2020 Data Integration

### PR DESCRIPTION
**Pull request by cmgosnell**
This PR integrates 2020 data for:
* EIA 860 (+EIA 860m to 2021-08)
* EIA 861
* EIA 923
* FERC 1
* FERC 714

Stuff that has to happen before it can be merged into `dev`:
* [x] Tox tests pass
* [x] `tox -e full` passes
* [x] `tox -e validate` passes (w/ the exception of min/max row checks, which will change w/ other `dev` PRs)
* [x] README reflects 2020 data update
* [x] Release notes reflect 2020 data update
* [x] Dataset documentation reflects 2020 data update
* [x] Merge in`dev` changes related to `boiler_fuel_eia923` primary keys.
* [x] We've added "How to integrate a new year of data" page to docs, based on changes in the PR.

### CODE REVIEW

**Comment by zaneselvans** [comment]
Should we refrain from merging this into `dev` until it's all working? Or at least until the ETL through 2019 is working again?

**Comment by cmgosnell** [comment]
we should definitely wait till it's working. these new archives just failed bc there are new unmapped ferc utilities

**Comment by zaneselvans** [comment]
That's interesting that it would fail on umapped FERC utilities if it's trying to process the 2019 data. Like did they change the 2019 data? (entirely possible).

It looks like it also failed to extract a data file from the EIA 923 2019 archive, so maybe they've renamed files as well.

**Comment by zaneselvans** [comment]
I ran `tox -e nuke` overnight and the only remaining issues were the expected number of records in all the tables are off (because I haven't updated them yet) and the `energy_source_N_transport_M` columns in `gens_eia861` are null because it's still trying to map to the long labels, rather than using the codes, which is incompatible with the ENUM constraint. However, this is fixed on the `dedupe-metadata` branch, and I'm going to try and merge that in, so I'm going to go ahead and merge.

**Pull request merged**
