### PR TITLE
Add 10 second FTP timeout

### PR DESCRIPTION
**Pull request by karldw**
Let's see how this goes on Travis!

### CODE REVIEW

**Comment by karldw** [comment]
We could definitely switch to urllib instead of ftplib. Reading the docs on [urllib.request.Request](https://docs.python.org/3/library/urllib.request.html#urllib.request.Request), it sounds like user-agent (or any other header) is only accepted for HTTP requests.

> `headers` should be a dictionary, and will be treated as if [`add_header()`](https://docs.python.org/3/library/urllib.request.html#urllib.request.Request.add_header) was called with each key and value as arguments. This is often used to “spoof” the User-Agent header value

and 
> Headers are currently ignored by all handlers except HTTP handlers

**Comment by zaneselvans** [comment]
Have you been able to reproduce the slooooooooow downloads of FERC & EPA data locally? Do you want to go ahead and edit the .travis.yml script to make it try and pull down the slow data, so we can see how the timeout affects things?

Hmm, well, if FTP ignores all headers then I don't know why it downloads fast from the browser, but slow via the command line. Any thoughts? I thought maybe it was because I was downloading from outside the US, but again, the fast browser doen't fit with that. Hmm.

**Comment by karldw** [comment]
The command-line version works quickly (enough) on my computer:

```sh
$ time python update_datastore.py --clobber --sources epacems --years 2017 --states ID

Downloading epacems data for 2017...

real	0m11.182s
user	0m1.356s
sys	0m0.109s

```

**Comment by karldw** [comment]
Adding a timeout didn't solve the problem, so I'm closing this PR.

**Pull request closed without merging**
