### PR TITLE
Ensure correct dtypes in EIA-930 CSV extract.

### PR DESCRIPTION
**Pull request by zaneselvans**
# Overview

Previously almost all numerical columns in the EIA-930 extraction were appearing as type `object` because in the CSV they show up as quoted strings with commas separating every 3 digits.

This PR ensures that those columns are parsed as numbers, and the datetime columns are parsed as datetimes when the CSVs are first read in, dramatically reducing overall memory usage, and avoiding the need to deal with enormous untyped dataframes in the transform steps.

However, this is kind of a hack, which overrides the entire `load_source()` method for the `CsvExtractor` class, and which really needs to be able to pass different arguments in to `read_csv()` depending on which of the several dataframes is being extracted. What's a better way to do that?

# Testing

How did you make sure this worked? How can a reviewer verify this?

```[tasklist]
# To-do list
- [ ] If updating analyses or data processing functions: make sure to update or write data validation tests (e.g.,  `test_minmax_rows()`)
- [ ] Update the [release notes](../docs/release_notes.rst): reference the PR and related issues.
- [ ] Ensure docs build, unit & integration tests, and test coverage pass locally with `make pytest-coverage` (otherwise the merge queue may reject your PR)
- [ ] Review the PR yourself and call out any questions or issues you have
- [ ] For minor ETL changes or data additions, once `make pytest-coverage` passes, make sure you have a fresh full PUDL DB downloaded locally, materialize new/changed assets and all their downstream assets and [run relevant data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation) using `pytest` and `--live-dbs`.
- [ ] For significant ETL, data coverage or analysis changes, once `make pytest-coverage` passes, ensure the full ETL runs locally and [run data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation) using `make pytest-validate` (a ~10 hour run). If you can't run this locally, run the `build-deploy-pudl` GitHub Action (or ask someone with permissions to). Then, check the logs on the `#pudl-deployments` Slack channel or `gs://builds.catalyst.coop`.
```

### CODE REVIEW

**Comment by e-belfer** [comment]
This is absolutely the right and intended place to do this, in my opinion.

**Comment by zaneselvans** [comment]
The problem I'm seeing here is that we potentially need to send different args to`read_csv()` depending on *which* of the (in this case 3) dataframes are being extracted, so just overriding the method at the level of EIA-930 isn't specific enough.  What I've got there now works for the `balance` table, but it doesn't do the right thing for the other two tables.

**Comment by e-belfer** [comment]
Does the `parse_dates` parameter want to be a function of either `filename` or the `**partition`, then?

**Comment by zaneselvans** [comment]
Closing this because it's been pulled into #3579

**Pull request closed without merging**
