### PR TITLE
Add Travis files, borrowing heavily from pandas

### PR DESCRIPTION
**Pull request by karldw**
- Minor edits to `environment.yml`
    - `matplotlib` is used in analysis.py
    - `dbfread` is in conda now
- The py.test markers in `setup.cfg` need some thought
- Progress toward #147

### CODE REVIEW

**Comment by karldw** [comment]
Getting this running will eventually require a Travis account https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI

This isn't urgent; we still need to figure out which tests we can run in a reasonable amount of time.

**Comment by zaneselvans** [comment]
My sense is we need to create a whole separate set of tests that depend only on a very small subset of the data, which is set aside from the multi-GB datastore, for the purposes of CI. The tests we have now, that take like 40 minutes to run on my machine, obviously exercise the software, but they also "test" the integration and cleaning of the data itself, by running it all through ETL, which I gather is not really what CI is meant for.  Does that sound correct to others?

Great that `dbfread` is in conda now! And if we get the in-memory file thing working with the raw_copy like in that example, maybe we can end up without any outside dependencies.

**Comment by zaneselvans** [comment]
@karldw I've set up an open source account for Catalyst with Travis CI, and added the Travis app to all of these repositories.

**Comment by karldw** [comment]
Oops, those are both mistakes. 

I do think it's worth specifying version info, at least for some packages. At one point I did a `conda update --all` and broke my configuration, but I forget the details.

I don't think there's any harm in accepting broken CI files. I don't think Travis will run anything until it has an appropriate secret [here](https://github.com/catalyst-cooperative/pudl/pull/179/files#diff-354f30a63fb0907d4ad57269548329e3R13).

**Comment by zaneselvans** [comment]
Is it just me, or does it seem a bit odd to have the secret token checked into a publicly readable repository?

**Pull request merged**
