### PR TITLE
Add PUDL citation for Grid Strategies load growth report.

### PR DESCRIPTION
**Pull request by zaneselvans**
# Overview

Add a citation to a report on resurgent US electricity load growth which relied on PUDL data.

# Testing

I built the docs locally and looked at the bibliography page and all was good.

```[tasklist]
# To-do list
- [x] Ensure docs build passes locally
```

### CODE REVIEW

**Review by e-belfer — APPROVED** [review]
Looks correct in the read the docs build.

**Comment by yashpandey06** [comment]
@zaneselvans  Hey! Before opening a pull request after making changes to the documentation, could you guide me on whether I need to run a specific command to ensure the documentation builds correctly? Any instructions on this would be greatly appreciated!

**Comment by zaneselvans** [comment]
@yashpandey06 if you'd like to build the docs locally, once you've installed and activated the `pudl-dev` conda environment, you should be able to run

```console
make docs-build
```

from within the top level PUDL repository.  You can look in the `Makefile` to see the commands that it's running.

**Comment by yashpandey06** [comment]
@zaneselvans thanks for you kind response , actually i am using the windows response so the make command isn't working can you help me out with some alternative of it !!

**Pull request merged**
