### PR TITLE
add new duke training data for FERC-EIA record linkage

### PR DESCRIPTION
**Pull request by cmgosnell**
# PR Overview
This PR adds training data for Duke utilities for the granular FERC-EIA record linkage process.

The manual mapping process was done in this sheet: [all_years_DUKE_fix_FERC-EIA_overrides.xlsx](https://github.com/catalyst-cooperative/pudl/files/10944367/all_years_DUKE_fix_FERC-EIA_overrides.xlsx)

This data has been run through the validation process and was added via the `validate_and_integrate_FERC1-EIA_manually_mapped_records` notebook.

Because this PR is overriding some of the existing Duke training data (2018-2020), I want to spend a little bit more time with those records because they were highly scrutinized.

# PR Checklist

- [x] Merge the most recent version of the branch you are merging into (probably `dev`).
- [ ] All CI checks are passing. [Run tests locally to debug failures](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#running-tests-with-tox)
- [ ] Make sure you've included good docstrings.
- [ ] For major data coverage & analysis changes, [run data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation)
- [ ] Include unit tests for new functions and classes.
- [ ] Defensive data quality/sanity checks in analyses & data processing functions.
- [ ] Update the [release notes](https://catalystcoop-pudl.readthedocs.io/en/latest/release_notes.html) and reference reference the PR and related issues.
- [ ] Do your own explanatory review of the PR to help the reviewer understand what's going on and identify issues preemptively.

### CODE REVIEW

**Comment by cmgosnell** [comment]
# RL results
### last night's results
```
2023-03-10 12:22:27 [    INFO] catalystcoop.pudl.analysis.ferc1_eia:506 Scores from the best model:
    Accuracy:  0.91
    F-Score:   0.94
    Precision: 0.94
    Recall:    0.94

2023-03-10 12:22:28 [    INFO] catalystcoop.pudl.analysis.ferc1_eia:594 Matches stats:
Percent of training data matches correctly predicted: 0.88
Percent of training data overwritten in matches: 0.078

2023-03-10 12:22:34 [    INFO] catalystcoop.pudl.analysis.ferc1_eia:858 Coverage for matches during EIA working years:
    Fuel type: 96.6%
    Tech type: 95.7%
Coverage for all steam table records during EIA working years:
    EIA matches: 80.0%
Coverage for all small gen table records during EIA working years:
    EIA matches: 51.9%
Coverage for all hydro table records during EIA working years:
    EIA matches: 90.2%
Coverage for all pumped storage table records during EIA working years:
    EIA matches: 66.8%
```


### w/ duke (and everything on @aesharpe 's branch)
```
2023-03-10 11:59:11 [    INFO] catalystcoop.pudl.analysis.ferc1_eia:506 Scores from the best model:
    Accuracy:  0.93
    F-Score:   0.95
    Precision: 0.95
    Recall:    0.95

2023-03-10 11:59:11 [    INFO] catalystcoop.pudl.analysis.ferc1_eia:594 Matches stats:
Percent of training data matches correctly predicted: 0.85
Percent of training data overwritten in matches: 0.064

2023-03-10 11:59:13 [    INFO] catalystcoop.pudl.analysis.ferc1_eia:858 Coverage for matches during EIA working years:
    Fuel type: 96.6%
    Tech type: 95.6%
Coverage for all steam table records during EIA working years:
    EIA matches: 82.0%
Coverage for all small gen table records during EIA working years:
    EIA matches: 52.1%
Coverage for all hydro table records during EIA working years:
    EIA matches: 90.2%
Coverage for all pumped storage table records during EIA working years:
    EIA matches: 70.5%
```

**Review by aesharpe — APPROVED** [review]
Yay, new training!!

**Comment by aesharpe** [comment]
I think these test fails are due to timeouts caused by multiple other ci tests running simultaneously...can rerun them again when there is less traffic.

**Comment by zaneselvans** [comment]
It looks like the `bandit` issues to me.

**Comment by jdangerx** [comment]
Looks like bandit to me, too - here's the relevant bit from [that latest failed run ❌:](https://github.com/catalyst-cooperative/pudl/actions/runs/4386777078/jobs/7767479523)

```
Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Run started:2023-03-15 16:12:19.517520

Test results:
>> Issue: [B608:hardcoded_sql_expressions] Possible SQL injection vector through string-based query construction.
   Severity: Medium   Confidence: Low
   CWE: CWE-89 (https://cwe.mitre.org/data/definitions/89.html)
   More Info: https://bandit.readthedocs.io/en/1.7.5/plugins/b608_hardcoded_sql_expressions.html
   Location: src/pudl/extract/ferc1.py:886:8
885	    return pd.read_sql(
886	        f"""
887	        SELECT {table_name_full}.*, {id_table}.report_year FROM {table_name_full}
888	        JOIN {id_table} ON {id_table}.filing_name = {table_name_full}.filing_name
889	        WHERE {id_table}.report_year BETWEEN :min_year AND :max_year;
890	        """,
891	        con=ferc1_engine,

--------------------------------------------------
>> Issue: [B113:request_without_timeout] Requests call without timeout
   Severity: Medium   Confidence: Low
   CWE: CWE-400 (https://cwe.mitre.org/data/definitions/400.html)
   More Info: https://bandit.readthedocs.io/en/1.7.5/plugins/b113_request_without_timeout.html
   Location: src/pudl/helpers.py:174:8
173	    }
174	    r = requests.get(url, stream=True, headers=headers)
175	    with save_path.open(mode="wb") as fd:

--------------------------------------------------

Code scanned:
	Total lines of code: 468[76](https://github.com/catalyst-cooperative/pudl/actions/runs/4386777078/jobs/7767479523#step:10:77)
	Total lines skipped (#nosec): 2
	Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 3

Run metrics:
	Total issues (by severity):
		Undefined: 0
		Low: 0
		Medium: 2
		High: 0
	Total issues (by confidence):
		Undefined: 0
		Low: 2
		Medium: 0
		High: 0
Files skipped (0):
ci: exit 1 (5.08 seconds) /home/runner/work/pudl/pudl> bandit -r src/pudl/ -c .bandit.yml pid=3996
.pkg: _exit> python /home/runner/micromamba-root/envs/pudl-test/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  ci: FAIL code 1 (113.17=setup[92.89]+cmd[0.10,6.57,0.32,0.28,5.85,0.65,0.43,0.[78](https://github.com/catalyst-cooperative/pudl/actions/runs/4386777078/jobs/7767479523#step:10:79),0.19,5.08] seconds)
  evaluation failed :( ([113](https://github.com/catalyst-cooperative/pudl/actions/runs/4386777078/jobs/7767479523#step:10:114).39 seconds)
Error: Process completed with exit code 1.```

**Pull request merged**
