### PR TITLE
Fix some pudl_id mapping

### PR DESCRIPTION
**Pull request by aesharpe**
Steve updated the pudl id mapping for plants brame and rodemacher and utilities
wheeling power co and cheyenne light and power.

The only changes are to the `pudl_id_mapping.xlsx` spreadsheet

### CODE REVIEW

**Comment by zaneselvans** [comment]
Have you tried running the full ETL with this version of the spreadsheet?

**Comment by aesharpe** [comment]
> Have you tried running the full ETL with this version of the spreadsheet?

I'm gonna do that tonight

**Review by zaneselvans — APPROVED** [review]
It passes CI here. I'm going to merge it into `dev` and run `tox -e nuke` overnight!

**Comment by zaneselvans** [comment]
Looks like there's one missing unmapped EIA Utility ID. After running the full ETL, this test will fail:

```
pytest --live-dbs test/integration/glue_test.py::test_unmapped_utils_eia
```
Giving this error:
```

    def test_unmapped_utils_eia(pudl_settings_fixture, pudl_engine):
        """Check for unmapped EIA Plants."""
        unmapped_utils_eia = get_unmapped_utils_eia(
            pudl_engine)
        if not unmapped_utils_eia.empty:
>           raise AssertionError(
                f"Found {len(unmapped_utils_eia)} unmapped EIA utilities, expected 0."
                f"{unmapped_utils_eia}"
            )
E           AssertionError: Found 1 unmapped EIA utilities, expected 0.                 utility_name_eia  capacity_mw  link_to_ferc1
E           utility_id_eia                                               
E           20521           wheeling power co          NaN          False

test/integration/glue_test.py:132: AssertionError
```

**Comment by zaneselvans** [comment]
Fixed this with PR #1480

**Comment by aesharpe** [comment]
Thanks for fixing this!

**Pull request merged**
