### PR TITLE
WIP: Make PPL process more memory efficient

### PR DESCRIPTION
**Pull request by katie-lamb**
After some changes made to the plant part list inputs the plant part list creation process uses too much memory for the RMI CI GitHub runners. This PR makes some changes to the plant part list process so that the RMI CI can pass.

### CODE REVIEW

**Comment by zaneselvans** [comment]
Did the memory usage increase happen to correspond with using pandas 1.5.0? Or is this just coincidental and independent from #1945 ?

**Comment by katie-lamb** [comment]
The increase in memory usage was independent of the pandas update. I'm not entirely sure what happened but maybe a change with the MCOE or EIA 860 tables?

**Comment by katie-lamb** [comment]
This was resolved in the RMI repo. The CI no longer uses too much memory and passes so I'm closing this PR.

**Comment by zaneselvans** [comment]
@katie-lamb can we also delete the `rmi-ppl-mem-fix` branch if it's no longer valuable?

**Pull request closed without merging**
