### PR TITLE
Fix Github Ref bug

### PR DESCRIPTION
**Pull request by bendnorman**
I forgot to pass the updated git ref to the GCE VM which resulted in incorrectly named buckets. This PR fixes that issue and renames the variable in the GitHub action.

I'm going to rerun the action before I merge it in.

### CODE REVIEW

**Review by zaneselvans — APPROVED** [review]

**Comment by bendnorman** [comment]
Hmmm the 3.10 tests are failing on some imputation tests :/

**Comment by zaneselvans** [comment]
Oh weird. I thought that was just a problem with the new numpy v1.23.0. This seems like a dependency update problem...

**Comment by bendnorman** [comment]
The [`build-deploy-pudl` branch](https://github.com/catalyst-cooperative/pudl/pull/1703) was the most recent branch to get merged in which passed the tests in 3.10. These are the only changes in dependencies:
- openssl 3.0.3 -> 3.0.4
- xyzservices 2022.4.0 -> 2022.6.0

I don't think either of those libraries touch the failing tests.

**Comment by zaneselvans** [comment]
It's `numpy==1.23` causing the problem. `main` is only pinned to <2.0. Updating it now.

**Comment by zaneselvans** [comment]
It looks like there are a couple of regressions in numpy that have come up this morning:

https://github.com/numpy/numpy/issues

**Comment by bendnorman** [comment]
Ohhh I see thank you Zane!

**Pull request merged**
