### PR TITLE
Update PUDL to use Python 3.11

### PR DESCRIPTION
**Pull request by zaneselvans**
# PR Overview

[Dagster doesn't yet support Python 3.11](https://discuss.dagster.io/t/8205077/hello-are-the-plans-to-add-support-for-python-3-11-thanks) but should soon.  All of our other dependencies do, so we'd like to upgrade once Dagster is ready. Some benefits:

* 3.11 is 25-60% faster than 3.10.
* 3.11 has more targeted error messages, indicating what portion of a statement is causing an error.

## PR Checklist

Before requesting a review of your pull request, please make sure you've done the
following:

* [ ] Merge the most recent version of `dev` (or the appropriate upstream branch) into
      your branch and resolved any merge conflicts. You may need to do this several
      times over the course of a PR as `dev` changes frequently.
* [ ] Verify that all of the CI checks on your PR are passing. See
      [Running Tests with Tox](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#running-tests-with-tox)
      for details on how to run the full test suite locally if you need to debug a
      particular failure.
* [x] Update the
      [release notes](https://catalystcoop-pudl.readthedocs.io/en/latest/release_notes.html)
      to reflect your changes. Make sure to reference the PR and any related issues.
* [x] Do your own review of the PR. Add comments highlighting areas where you have
      questions you'd like reviewers to answer, known issues, solutions you're
      unsatisfied with, or other things that deserve special attention from the
      reviewer.

### CODE REVIEW

**Review by bendnorman — COMMENTED** [review]
This all looks good and fine to me. Unfortunately, dagster doesn't support 3.11 yet :/ I just asked in the dagster slack when they expect to update dagster to support 3.11.

In the meantime, we could either wait to update PUDL to use Python 3.11 and I can use 3.10 on the `dagster-asset-etl`. I'm partial to holding off on updating PUDL until dagster is updated so we don't get code and dependency conflicts between `dev` and `dagster-asset-etl`.

**Comment by zaneselvans** [comment]
Ah okay good to know. Let's just shelve this for now then. It was mostly just me wanting to know whether there was anything else blocking us from moving over. We can just keep an eye on the Dagster requirements and switch over when they do.

**Comment by bendnorman** [comment]
Sounds good! Someone in slack said they expect to support 3.11 early in the new year.

**Comment by zaneselvans** [comment]
Closing this and turning into an issue, since we'll merge Dagster into `dev` before it happens, and there are so many changes.

**Pull request closed without merging**
