### PR TITLE
Move slowly varying plant attributes from entity to annual plants table

### LINKED ISSUE #1748: Move slowly varying columns from plants_entity_eia to annual plants_eia860
In working on the EIA fuel price imputation (See #1708) it became clear that the EIA Sector ID assigned to a plant does change occasionally (e.g. when a plant is sold by a regulated utility to an IPP / merchant generator). This is one of the fields used in reporting aggregated fuel prices in the EIA API, which contains information about redacted prices.

To more accurately reflect this slow-changing variable and enable reproduction of the EIA aggregations, move `sector_id_eia` and `sector_name_eia` from the `plants_entity_eia` table (which contains fixed attributes) to the `plants_eia860` table, which contains annual attributes.

While I'm in here shuffling these fields around.... here are the fixed plant attributes:
```py
        "static_cols": [
            "balancing_authority_code_eia",  # moved to plants_eia860
            "balancing_authority_name_eia",  # moved to plants_eia860
            "city",
            "county",
            "ferc_cogen_status",  # moved to plants_eia860
            "ferc_exempt_wholesale_generator",  # moved to plants_eia860
            "ferc_small_power_producer",  # moved to plants_eia860
            "grid_voltage_2_kv",  # moved to plants_eia860
            "grid_voltage_3_kv",  # moved to plants_eia860
            "grid_voltage_kv",  # moved to plants_eia860
            "iso_rto_code",  # moved to plants_eia860
            "latitude",
            "longitude",
            "plant_name_eia",
            "primary_purpose_id_naics",  # moved to plants_eia860
            "state",
            "street_address",
            "zip_code",
        ],
```

Others that I think should probably be allowed to vary annually, due to the fact that their territories shift over time:
* `balancing_authority_code_eia`
* `balancing_authority_name_eia`
* `iso_rto_code`

Other possibilities...
* `primary_purpose_id_naics` -- as with `sector_id_eia` it seems like this could change when plants are bought & sold. Seems like this should definitely be annual, if the high level EIA sector code is, since the EIA sector is derived from this ID.
* `ferc_exempt_wholesale_generator` -- probably doesn't change often, but seems like [it can change occasionally](https://www.ferc.gov/industries-data/electric/power-sales-and-markets/exempt-wholesale-generators-ewg).
* `ferc_small_power_producer`, `ferc_cogen_status` -- Determined by [FERC Form 556](https://www.ferc.gov/qf), probably wouldn't ever go back once the status has been assigned, but might not have always been a qualifying facility.
* `grid_voltage_*` -- do grid ties change / get upgraded over time?

@TrentonBush do you have thoughts?

### PR DESCRIPTION
**Pull request by zaneselvans**
Closes #1748

### CODE REVIEW

**Comment by zaneselvans** [comment]
Somewhat to my surprise the full ETL, all the tests, and validations passed!

**Comment by TrentonBush** [comment]
I was confused as to why moving balancing authority codes didn't mess up FERC 714 but TIL it uses EIA861 BA codes, not the harvested ones.
Anyway we have no code that references these columns? It seems like our tests check expected # of rows but not columns, so it wouldn't surprise me if they are different and we just don't know it yet. A lot of the downstream code is untested analysis modules (or client/user code 😬). `output.eia_860.generators_eia860` aka `pudl_out.gens_eia860` in particular looks like it would lose all the columns that are moved, and that gets called all over the place in analysis modules

**Comment by TrentonBush** [comment]
Since you've already run the full etl locally with this branch, maybe we can check the `.shape` of all the pudl_out objects against their `dev` branch counterparts?

**Comment by zaneselvans** [comment]
The outputs which assemble parts from the entity and annual tables generally aren't picking and choosing specific columns, they just bring together everything in those tables, broadcasting the fixed values across the annual records, so analyses that depend on the denormalized outputs don't generally notice when a column moves between these tables.

```py
    # grab the entity table
    plants_eia_tbl = pt["plants_entity_eia"]
    plants_eia_select = sa.sql.select(plants_eia_tbl)
    plants_eia_df = pd.read_sql(plants_eia_select, pudl_engine)

    # grab the annual table select
    plants_eia860_tbl = pt["plants_eia860"]
    plants_eia860_select = sa.sql.select(plants_eia860_tbl)
```

But yeah it looks like the `generators_eia860` output function does only merge in data from the `plants_entity_eia` table, and not the annual table. To my knowledge none of the columns which got moved have been used in anything downstream (famous last words!). They're mostly pretty obscure attributes and the generators table has more than 100 columns.

I really look forward to having well defined schemas for the database views that replace this janktastic output table arrangement.

We haven't yet created an entity table for the balancing authorities (which are primarily sourced from EIA 861) so the harvesting / normalization just treats the BA codes like a plant attribute.

I looked at all of the `_eia860` and `_eia923` output tables, as well as all the outputs related to the `mcoe` calculation and the `plant_parts_eia` and the only places where there were changes in the set of columns that appeared in the output were, as expected the `gens_eia860` output.

There was also the renaming of `plants_eia860.grid_voltage_kv` to `plants_eia860.grid_voltage_kv_1` and the recent change that moved the `fuel_group_code` from the FRC table into the energy sources EIA table, but that's already been merged in, and had no effect since we haven't previously been using it, and it's been replaced with `fuel_group_eiaepm`). So, the set of symmetric diffs of the column outputs were:

```py
plants_eia860: {
    'grid_voltage_1_kv',
    'grid_voltage_kv'
}
gens_eia860: {
    'sector_name_eia',
    'ferc_cogen_status',
    'primary_purpose_id_naics',
    'ferc_small_power_producer',
    'grid_voltage_3_kv',
    'sector_id_eia',
    'iso_rto_code',
    'balancing_authority_code_eia',
    'grid_voltage_2_kv',
    'grid_voltage_kv',
    'balancing_authority_name_eia',
    'ferc_exempt_wholesale_generator'
}
frc_eia923: {
    'fuel_group_code'
}
```

So it doesn't look like there are any weird downstream consequences for the main analysis modules we use frequently.  This makes sense since those are both getting tested in the integration tests.

**Comment by zaneselvans** [comment]
You mean merge the annual plant columns into the generators output table? I thought about doing that, but it would introduce dozens of new columns and I'm worried it might result in name collisions or other unexpected behavior.

**Comment by TrentonBush** [comment]
We could merge in only the columns that were there previously. But I take it that backwards compatibility isn't a priority here? Not sure where the dev cycle is on that.

**Comment by zaneselvans** [comment]
We're still `v0.x.y` so... we're not promising to avoid breaking changes (though of course that's always nice).  And the way the system is built right now, it's a nightmare to ensure nothing changes. I think once we have things in a more data-warehousey setup it'll be more possible to ensure that the schemas of core assets are stable.

I just looked at trying to merge in the annual plants stuff and it'll run into some plant+utility columns that we merge into all of the output tables. So they could be added to all of the outputs, we could try and work around them here, but nothing we're testing is breaking with these changes, and we want to get rid of the output functions *entirely* as soon as possible, so I would really just like to get it merged in, and get the fuel price estimates done with ASAP so we can do a release and move on to actually refactoring the system to be maintainable.

**Comment by TrentonBush** [comment]
Fair enough!

**Review by TrentonBush — APPROVED** [review]

**Comment by zaneselvans** [comment]
Of course backward compatibility is important! But with the DB schemas and naming of things... if we can never change anything, then we're trapped with the bad, uninformed choices we made early on. So then creating anything new becomes super stressful and high stakes because it'll be frozen like that forever.

**Pull request merged**
