### PR TITLE
Add EPA CEMS hourly

### PR DESCRIPTION
**Pull request by karldw**
- Currently the download is *very slow*, probably for FTP reasons.

More CEMS stuff on the way!

### CODE REVIEW

**Comment by karldw** [comment]
This isn't urgent, but when you have a chance, could you let me know if these changes seem reasonable?

Also, I'm not sure how to add a table to the `pudl.models.entities.PUDLBase.metadata.tables`.  Is it in the glue?

Most importantly, we should talk about identifiers! The CEMS has ORISPL codes, which are the same as the EIA plant IDs. The CEMS also has unit IDs, which [apparently](https://www.epa.gov/sites/production/files/2018-02/documents/egrid2016_technicalsupportdocument_0.pdf#page=18) map to EIA 923 unit/generator IDs, but I haven't tried yet.




Crossref #171

**Comment by zaneselvans** [comment]
Hmm, so the EIA plant_ids are a subset of a larger universe of ORISPL codes, which are controlled by EPA?

The table definitions that appear inside the PUDLBase metadata object are added automatically when a new table is defined that descends from the PUDLBase object (this is all SQLAlchemy stuff). If you look at, say, models/eia860.py you'll see a bunch of classes which descend from PUDLBase, and each of them defines a table, including foreign key relationships, primary keys, data types, etc. When those class definitions are imported, they populate the metadata object which contains a schema like definition of the DB structure. Does that make sense?

**Comment by karldw** [comment]
Ah!  Sorry, I meant to add that you shouldn't merge yet. This is currently broken because I haven't integrated correctly with SQLAlchemy.

**Comment by zaneselvans** [comment]
Whoops. At first I thought this was just changing the udpate_datastore script to get the EPA CEMS data, but now I see this is much more extensive. Maybe we should have a call and talk about the pull request process and what you're thinking on the ETL process?

**Comment by karldw** [comment]
Partial list of things I need to change before this is merged, in no particular order:
- [ ] Fix slow FTP download
- [ ] Make SQLAlchemy ingest work
- [ ] Figure out fac_id and unit_id
  - What do they represent?
  - When when do they appear or disappear?
  - Do we want to keep them?
- [ ] Sort out any issues that prevent a plant-level foreign key relationship
- [ ] Look into issues with a unit-level foreign key relationship (this is much harder)
- [ ] Make the hourly measurements into intervals

**Comment by zaneselvans** [comment]
Why is the FTP download so egregiously slow? My god.  It looks like they've deprecated the FTP server that is currently listed in the constants module.  New one is:
ftp://newftp.epa.gov/DMDnLoad/emissions/hourly/monthly/

I swear I've come across he FAC_ID and UNIT_ID references for EPA before, but my cursory search is not turning them up now. I think keeping the IDs is a good idea, even if we don't know exactly what they link up to yet, for future reference.

On the EIA Plant/Unit IDs, I'm curious what the Units are going to refer to -- Until 2014, they weren't reporting generation units in a clear way -- boilers and generators were reported separately, with some incomplete associations between them (especially for gas plants). @cmgosnell just recently finished re-organizing our best attempt at extracting those associations from all the available boiler & generator info in EIA.

Like we chatted about, both pandas and postgres appear to have native support for time intervals as a data type, and we want to migrate all of our current timestamps to intervals/PeriodIndex objects for our indices. Right now there's an artificial convention to choose the beginning time of each reporting interval
* http://www.postgresqltutorial.com/postgresql-interval/
* https://pandas.pydata.org/pandas-docs/stable/generated/pandas.PeriodIndex.html

**Comment by gschivley** [comment]
Are you doing anything about datetimes? My approach has been to convert everything to UTC. CEMS reports all times in local standard time, which means no daylight savings. If you aren't already taking care of this I can at least outline my approach.

**Comment by karldw** [comment]
Ugh, [timezones](https://xkcd.com/1883/). No, I haven't dealt with that yet. It'd be good to deal with those at the same time as I convert to interval/periodindex (see Zane's comment above).

**Comment by karldw** [comment]
Using an FTP connection seems useful. I think it's still helpful to separate the download and processing steps, so my first choice is to avoid downloading directly with pandas.

**Comment by zaneselvans** [comment]
We've got the lat/lon for each of the plants from EIA860, so in theory we should be able to figure out the UTC offset (please god, someone must have already written that package). For a lot of analysis, I think it'll be most useful to have the option of putting things in local time -- since load curves are pretty tightly bound to the diurnal cycle.

On a structurally related note (and related to the first comment @karldw made on the whole project) at some point we probably need to shift all of the financial data into inflation adjusted dollars.

**Comment by gschivley** [comment]
Some lat/lon are missing from earlier versions of 860 but you might be good from 2011 onward.

Check out **a location's time zone offset from UTC in minutes** in the [timezonefinder README] (https://github.com/MrMinimal64/timezonefinder). Keep in mind that CEMS reports all values in standard time (no daylight savings) so the solution provided there has to be modified. I changed
```Python
today = datetime.now()
```
to 
```Python
# Provide a reference date during standard time (winter)
# Do this by setting the month from datetime.now() to 1 (january)
# This date will be used to determine the offset from UTC at the timezone
ref_date = datetime.now().replace(month=1)
```

Storing all datetimes in UTC ensures that times will accurately match in a regional analysis (e.g. NERCs or eGRID subregions). Offset in hours for each plant can be stored in a separate table.

**Comment by zaneselvans** [comment]
@karldw where are you at on this pull request? Are you working with these changes locally? Is feedback from us holding you up on checking it in? @cmgosnell and @alanawlsn and I will probably be working together for some part of tomorrow. We can try and get some comments pulled together for you if that would be useful.

**Comment by karldw** [comment]
@zaneselvans, I think I have a working version, but it's really slow, and I wanted to run `init_pudl.py` at least once before pushing out the code. (And that's not even running the tests)

**Pull request merged**
