### PR TITLE
Merge EIA861 short-form transform

### LINKED ISSUE #3540: Transform the EIA-861 short form table
Smaller utilities report an abbreviated version of the EIA-861, called the short form.  This data is currently being extracted into an asset named `raw_eia861__short_form`, but as noted by @gschivley it's not getting transformed and written to the database, so what information we have about these smaller load serving entities is currently getting lost. This data started being reported in 2012, and is available up through the present (most current EIA-861 data is 2022).

## Complications
- In 2019, the EIA-861 Short Form data was intermingled with all the other Long Form data. So there's a gap in the reporting, and all of that other 2019 Short Form data will need to be extracted from the other various tables, or this data would need to be put into those tables for internal consistency.
- Note that because the EIA-861 tables are not yet being harvested to extract utility IDs, no foreign key relationship can be defined between this table and the existing utility entity tables.

```[tasklist]
- [ ] The column mapping that lets us extract this data from the spreadsheets should be updated to use the same naming conventions as the rest of PUDL. E.g. `ba_code` should be `balancing_authority_code_eia`. Most of these columns should already be defined in `pudl.metadata.fields`. The column mappings are stored in `src/pudl/package_data/eia861/column_maps/short_form_eia861.csv`
- [ ] A new `core_eia861__yearly_short_form()` asset will need to be defined in `pudl.transform.eia861`
- [ ] Columns will need to be cleaned up to have appropriate NA values and to conform to the appropriate data types. See the other transform functions for examples. It looks like there  are a number of boolean columns which currently contain `Y` or `N`. There may also be columns where only certain values are valid, which need to be cleaned up (e.g. do all state abbreviations actually correspond to a real state?)
- [ ] The new `short_form` table should be integrated into the processes downstream which compile the table of balancing authorities
- [ ] Either the 2019 short form data will need to be extracted from the other tables where it was reported and added to this one, or the contents of this table will need to be added to all those other tables.
- [ ] If we're adding a new table to the PUDL DB, it will need to have a schema defined in `pudl.metadata.resources.eia861`
```

```py
from pudl.etl import defs
short_form = defs.load_asset_value(AssetKey("raw_eia861__short_form"))
short_form.info()
```
```
RangeIndex: 13015 entries, 0 to 13014
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ba_code                 11449 non-null  object 
 1   demand_side_management  13001 non-null  object 
 2   early_release           0 non-null      object 
 3   entity_type             9648 non-null   object 
 4   green_pricing           1124 non-null   object 
 5   net_metering            12999 non-null  object 
 6   report_year             13015 non-null  float64
 7   state                   13015 non-null  object 
 8   time_based_programs     13001 non-null  object 
 9   total_customers         13015 non-null  object 
 10  total_revenue           13015 non-null  object 
 11  total_sales             13015 non-null  object 
 12  utility_id_eia          13015 non-null  float64
 13  utility_name_eia        13015 non-null  object 
 14  water_heater            11891 non-null  object 
 15  data_maturity           13015 non-null  object 
dtypes: float64(2), object(14)
memory usage: 1.6+ MB
```

```py
short_form.sample(10)
```
|      | ba_code   | demand_side_management   |   early_release | entity_type   | green_pricing   | net_metering   |   report_year | state   | time_based_programs   |   total_customers |   total_revenue |   total_sales |   utility_id_eia | utility_name_eia                     | water_heater   | data_maturity   |
|-----:|:----------|:-------------------------|----------------:|:--------------|:----------------|:---------------|--------------:|:--------|:----------------------|------------------:|----------------:|--------------:|-----------------:|:-------------------------------------|:---------------|:----------------|
| 2338 | WACM      | N                        |             nan | nan           | nan             | Y              |          2014 | CO      | N                     |              3056 |          5670   |         53658 |             5036 | City of Delta - (CO)                 | .              | final           |
| 6980 | MISO      | N                        |             nan | Municipal     | nan             | Y              |          2018 | IL      | N                     |              3586 |          8206   |         59329 |            11790 | City of Mascoutah - (IL)             | .              | final           |
| 1757 | CPLE      | N                        |             nan | nan           | nan             | N              |          2013 | NC      | N                     |              1122 |          2038.5 |         18427 |            11205 | Town of Lucama - (NC)                | .              | final           |
| 9029 | PNM       | N                        |             nan | Cooperative   | nan             | Y              |          2020 | NM      | Y                     |              4313 |          7456   |         45100 |            23326 | Sierra Electric Coop, Inc            | .              | final           |
|  696 | nan       | N                        |             nan | nan           | N               | N              |          2012 | MN      | N                     |              1931 |          3182.9 |         27943 |            13681 | North Branch Water & Light Comm      | nan            | final           |
|  807 | nan       | Y                        |             nan | nan           | N               | N              |          2012 | IA      | N                     |               377 |           540   |          4563 |            15751 | City of Readlyn - (IA)               | nan            | final           |
| 5460 | ERCO      | N                        |             nan | Municipal     | nan             | N              |          2016 | TX      | N                     |              3019 |          8932   |         69610 |             2050 | City of Bowie - (TX)                 | .              | final           |
| 8653 | MISO      | N                        |             nan | Municipal     | nan             | N              |          2020 | MN      | N                     |               210 |           238   |          2087 |            16451 | City of Rushmore - (MN)              | .              | final           |
| 8659 | MISO      | N                        |             nan | Municipal     | nan             | N              |          2020 | MN      | N                     |              1245 |          2940   |         20852 |            17836 | Springfield Public Utils Comm - (MN) | .              | final           |
| 4479 | WACM      | N                        |             nan | Municipal     | nan             | N              |          2015 | WY      | N                     |               772 |           938.5 |         10273 |            15051 | City of Pine Bluffs - (WY)           |                | final           |

### PR DESCRIPTION
**Pull request by zaneselvans**
# Overview

Closes #3540 and replaces @nancy9ice PR #3565 to get all the CI to run because permissions are hard.

# Testing

How did you make sure this worked? How can a reviewer verify this?

```[tasklist]
# To-do list
- [ ] If updating analyses or data processing functions: make sure to update or write data validation tests (e.g.,  `test_minmax_rows()`)
- [ ] Update the [release notes](../docs/release_notes.rst): reference the PR and related issues.
- [ ] Ensure docs build, unit & integration tests, and test coverage pass locally with `make pytest-coverage` (otherwise the merge queue may reject your PR)
- [ ] Review the PR yourself and call out any questions or issues you have
- [ ] For minor ETL changes or data additions, once `make pytest-coverage` passes, make sure you have a fresh full PUDL DB downloaded locally, materialize new/changed assets and all their downstream assets and [run relevant data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation) using `pytest` and `--live-dbs`.
- [ ] For significant ETL, data coverage or analysis changes, once `make pytest-coverage` passes, ensure the full ETL runs locally and [run data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation) using `make pytest-validate` (a ~10 hour run). If you can't run this locally, run the `build-deploy-pudl` GitHub Action (or ask someone with permissions to). Then, check the logs on the `#pudl-deployments` Slack channel or `gs://builds.catalyst.coop`.
```

### CODE REVIEW

**Review by jdangerx — APPROVED** [review]
This is a mirror of #3565 which was approved already. Only mirrored for CI workaround purposes.

**Comment by zaneselvans** [comment]
Okay, we've got some real integration test failures here:

```
FAILED test/integration/etl_test.py::test_pudl_engine - pudl.etl.check_foreign_keys.ForeignKeyErrors: Foreign key error for table: core_eia861__yearly_short_form -- core_eia__codes_balancing_authorities (code) -- on rows [    1     2     3 ... 11343 11982 12515]

Foreign key error for table: core_eia861__yearly_short_form -- core_eia__entity_utilities (utility_id_eia) -- on rows [    2     3     4 ... 13013 13014 13015]
FAILED test/integration/output_test.py::test_outputs_by_table_suffix[eia861] - ValueError: Found null column: short_form_eia861.num_water_heaters
```

**Comment by jdangerx** [comment]
Hi Nancy! We've been meeting in person for the last couple of days, thanks for your patience. Yes, `make pytest-coverage` should reflect what gets run in CI.

**Comment by Nancy9ice** [comment]
> Hi Nancy! We've been meeting in person for the last couple of days, thanks for your patience. Yes, `make pytest-coverage` should reflect what gets run in CI.

I understand. I've looked at the errors and it's because the values in the utility_id_eia and the balancing_authority_code_eia don't match values in the tables that also have these columns which is a bit odd. 

Also, there are null values in the num_water_heater columns. For this one, should I change the NULL values to zero instead?

**Comment by zaneselvans** [comment]
With the all NULL values for `num_water_heaters`... is it because that column doesn't exist or contain data in the years of data that are processed in the integration tests?  Or is it accidentally getting nulled in the transform somehow?  If you run the full ETL locally, is it also entirely NULL? It could also be a column naming error somewhere such that the real data is put into a column that's dropped when the database schema is enforced.

For the FK constraints, we might need to add some additional exceptions to the rules that are used to generate the constraints, since none of the EIA-861 tables are harvested -- i.e. they aren't used as the raw materials to construct the EIA Utility Entity table.  I'm not sure where the balancing authority code FK is pointing though, since we don't have an entity table for the BAs.  It might be that that column needs to be encoded / cleaned up in the short form table if it's got some bad / non-standard values in it.

I think @cmgosnell is going to pop in and take a look.

**Comment by Nancy9ice** [comment]
> With the all NULL values for `num_water_heaters`... is it because that column doesn't exist or contain data in the years of data that are processed in the integration tests? Or is it accidentally getting nulled in the transform somehow? If you run the full ETL locally, is it also entirely NULL? It could also be a column naming error somewhere such that the real data is put into a column that's dropped when the database schema is enforced.
> 
> For the FK constraints, we might need to add some additional exceptions to the rules that are used to generate the constraints, since none of the EIA-861 tables are harvested -- i.e. they aren't used as the raw materials to construct the EIA Utility Entity table. I'm not sure where the balancing authority code FK is pointing though, since we don't have an entity table for the BAs. It might be that that column needs to be encoded / cleaned up in the short form table if it's got some bad / non-standard values in it.
> 
> I think @cmgosnell is going to pop in and take a look.

For the num_water_heaters, if you check the raw data files, they are actually NULL. For example, all the water_heater rows in the 2022 short form table are NULL

**Comment by cmgosnell** [comment]
hey @Nancy9ice ! thanks for this insight! I went ahead and ran the CI tests locally and got the same results. I also generated this table with all of the years and it looks like this column is always null! So I'm going to add a defensive check in the transform to check if its always null and then remove it from the table.

And the FK problem is very expected with the 861 tables. This is an example of a quirk that don't have great documentation for ;-) 

I'll push some changes momentarily and hopefully we'll get this merged in.

**Pull request merged**
