### PR TITLE
Rollback pandas-1.5

### PR DESCRIPTION
**Pull request by bendnorman**
Since updating to pandas-1.5, our nightly builds have doubled in memory use. I'm opening this PR to test the memory use with pandas 1.4.x.

### CODE REVIEW

**Comment by bendnorman** [comment]
The nightly build for this branch passed on a 32 GB machine and has a memory profile similar to the builds before upgrading to pandas 1.5. Memory profiles:

nightly_build_memory_issues

Some potential pandas-1.5 bugs:
- Maybe we haven't found all of places we are downcast dates. See pandas-dev/pandas#48574
- Maybe our downcasting workaround isn't reducing memory? #1902 
- We use `.drop(inplace=True)` a lot which can blow up memory but was also present in 1.4.4. See pandas-dev/pandas#48682

**Comment by zaneselvans** [comment]
I'd be surprised if the downcasting solution wasn't reducing memory usage in the places where it's been applied. The blowup was happening because e.g. running `astype("datetime64[Y]")` on an hourly dataframe in pandas 1.5 results in... an hourly dataframe. So there were still a huge number of records, and then they got merged with other dataframes, leading to tens of millions of rows where there should only have been thousands.  The workaround that turns a Series into a Numpy array, downcasts, and then rebuilds a new Series definitely seemed to result in the right number of records.

I searched the codebase for any instance of `datetime64` with day/month/year resolutions and the only one I found outside the `report_date` formatting function was in the FERC-714 hourly demand table transform, which I fixed.

Maybe there are other ways that one might try and invoke the same behavior without explicitly mentioning the data type? Should we run a memory profiler and see where it explodes?

**Comment by bendnorman** [comment]
I'll profile the EIA ETL because its using 2x memory with pandas-1.5.

**Review by zaneselvans — APPROVED** [review]
Welp, it's annoying but I guess we should merge this into `dev` to get the nightly builds working again and re-open #1901 until we've hunted down the memory issue, or it's been fixed upstream.

**Pull request merged**
