### PR TITLE
Patch nightly build flakiness

### PR DESCRIPTION
**Pull request by bendnorman**
This PR retries GCS Cache requests on BadRequest errors to eliminate the flakiness in our nightly builds.

### CODE REVIEW

**Comment by zaneselvans** [comment]
The first attempt at running the tests failed with a Zenodo timeout, which seems weird to me. I thought we were trying to download directly from the GCS cache for the CI now?

**Comment by zaneselvans** [comment]
Hmm, it looks like we added the `--gcs-cache-path` argument to our pytest configuration, but then didn't tell the CI to use it.

**Comment by zaneselvans** [comment]
PR trying to use the GCS Cache in CI: https://github.com/catalyst-cooperative/pudl/pull/1858

**Review by zaneselvans — APPROVED** [review]

**Comment by bendnorman** [comment]
Ohh I thought the GCS cache in pytest changes were buried in an EIA flakiness PR. 

> Is there a good reason not to just have the tests default to trying the GCS cache first all the time? If there's a local cache, that'll get priority. If the data isn't in the GCS cache, it'll fall back to pulling from Zenodo (and populate the GCS cache in the process?)

This is currently how the `LayeredCache` works. If the files aren't available in the local cache, then it falls back to the GCS cache if `--gcs-cache-path` is specified. Are you saying we should set it up, so folks don't need to specify `--gcs-cache-path`?

**Pull request merged**
