### PR TITLE
Fix county FIPS codes string type in fuel_receipts_costs_eia923

### PR DESCRIPTION
**Pull request by katie-lamb**
In the EIA 923 extract `county_id_fips` is read in as a string and zero padded at the beginning to be a 3 digit county FIPS code. In transform the string type is maintained instead of casting to an int and float. In the `fuel_receipts_costs_eia923` output table `county_id_fips` is now a correctly formatted 3 digit string instead. 

To Do: 

- [x] Disambiguate that county FIPS apply to mines only not the plants - move this into transform instead of output?
- [ ] `county_id_fips` is still being stored as an Object in the `coalmine_eia923` output metadata table. The formatting is still correct (3 digit zero leading FIPS) could change to a string?
- [x] Change to five digit FIPS

### CODE REVIEW

**Comment by katie-lamb** [comment]
> In the other contexts where we've used them (e.g. the utility service territory generation / EIA-861 parsing) we've used the 5-digit county FIPS codes (two-digit state + 3 digit county), since that's they way they showed up in the Census DP1 data and it allows us to merge on a single column that uniquely identifies the county nationwide. Is there a good reason why we wouldn't want to do that in general? Or here in particular? The DP1 has 3 main tables at different spatial resolutions: state, county, and track, and they all use the full FIPS code (2, 5, or 11 digits, depending on the geometries they're referring to)

I went with the three digit county code because that's what was being given in the `fuel_receipts_costs_eia923` output table in the `county_id_fips` column (and it's what's used in the raw EIA923 data) and I wasn't sure if something else depended on this three digit county code. Since it seems like only full FIPS codes are used, I'll scrap this `county_id_fips` column and change it to just a five digit `fips` column. Seems like there's no reason I should keep this `county_id_fips` column.

**Comment by zaneselvans** [comment]
I think it should probably still be called `county_id_fips` -- that's what the other 5-digit county FIPS columns have been called. Just because the state and tract level IDs are also FIPS and it'll be good to be able to differentiate them.

**Comment by katie-lamb** [comment]
> I think it should probably still be called `county_id_fips` -- that's what the other 5-digit county FIPS columns have been called. Just because the state and tract level IDs are also FIPS and it'll be good to be able to differentiate them. The current column in the FRC table was just never really dealt with effectively. In general we've tried to have a `{thing}_{type}_{source}` naming convention, e.g. `generator_id_eia` or `plant_name_ferc1` where `type` is often one of `id`, `code`, or `name`.

The coalmine and fuel receipts costs transform now changes the three digit county FIPS to be the full five digit FIPS.
> 
> Should this be `coalmine_county_id_fips`? We haven't done a great job of differentiating between which entity a column is referring to when there's more than one possibility. E.g. with plant owners vs. operators in the `ownership_eia860` table.

The column is changed to `coalmine_county_id_fips` in the `fuel_receipts_costs_eia923` output table, but left as `county_id_fips` everywhere else.

**Review by zaneselvans — APPROVED** [review]
I added a regex constraint to the FIPS fields in the metdata so we know for sure that they all fit the 2 or 5 digit string format, and they do!

Gotta fix the ZIP codes too at some point, but that's more complicated because there are also some Canadian post codes. 🙄  See #550

**Pull request merged**
