### PR TITLE
Fix integration tests with XBRL data

### PR DESCRIPTION
**Pull request by zaneselvans**
This PR aims to fix integration tests broken by XBRL updates. It adds a new test fixture for managing the FERC1 XBRL database.

### CODE REVIEW

**Comment by zaneselvans** [comment]
This is weird! It looks like the test failure is due to an `ascii` encoding issue in the coal mine county column, and it happens when we try to add the FIPS code to the column based on the string that's coming from the spreadsheet representing the county name.

The `addfips` library is still v0.3.1 so that hasn't changed, and the raw EIA spreadsheet data hasn't changed recently (unless the ei923er data got in here somewhere which seems unlikely), so... maybe some other spreadsheet or string processing library version changed and is behaving differently now?

**Comment by zaneselvans** [comment]
@zschira if the tests are passing for you locally... have you updated your `pudl-dev` or `tox` environment lately? If you run `tox` by itself it'll run all of the CI tests and create its environment from scratch with whatever the new versions of all the dependencies are, so it should behave more similarly to the automated CI.

**Comment by zschira** [comment]
I'll go ahead and give it a try. I've just been running the integration tests alone, which are passing (minus EIA API issues).

**Comment by zaneselvans** [comment]
I wonder if this has to do with XML parsing somehow. Didn't you say you had to pull in some other XML parsing library to deal with the XBRL data?  I wonder if the packages that read the Excel spreadsheets (which are stored as XML internally) are using a different XML parsing library now than they did before and it deals with character encodings differently?

**Comment by zaneselvans** [comment]
Oh yeah you always gotta run `tox` to know for sure if things are actually working.

**Comment by zschira** [comment]
It seems like a dependency issue is likely. Particularly given that it's behaving differently locally vs here.

Also, I'm running just `tox` now and it hasn't completed yet, but it's almost done and I've only seen EIA API errors. I'll try and dig into the dependencies and see if I can find something. I think an XML library version difference seems like a good guess.

**Comment by zaneselvans** [comment]
This is maybe another indication that the initial extraction of the XBRL into SQLite should be separated from the main PUDL repo to avoid their dependencies interacting, since the SQLite DBs + json metadata can be handed off in isolation pretty effectively.

**Comment by zschira** [comment]
Yeah that's a good point. Do you think it would be worth doing as a part of the current work I'm doing to archive/publish all of the FERC XBRL forms? It would require separating the Datastore from PUDL, which is why I've been a bit hesitant to do it now, but maybe it's just better to do now to avoid more refactoring in the future.

**Comment by zaneselvans** [comment]
I think if we can get the tests back to passing with a minor change here that would be better for now probably. I just foresee more of this kind of issue coming up with the very different (and ever expanding) dependencies that different corners of the ETL process are taking on.

I think this is probably what the `Repository` abstraction is supposed to help manage in Dagster. Right @bendnorman? If we have the XBRL extractors and the DBF extractors isolated in their own (git) repositories, then they can each be brought in piecemeal to different Dagster repositories to generate their individual DBs (or maybe schemas within a PostgreSQL DB) which are the only bits that get handed off to the downstream portions of the DAG.

@cmgosnell what do you think?

**Comment by zschira** [comment]
It turns out Arelle was changing the locale for Python 2.7 support. In the mirror of Arelle that I created for packaging, I've removed this, and that has fixed the decode error (the change is in the file `arelle/locale.py`). I'm going to close this PR and merge in the fixes to `xbrl_integration`.

**Pull request closed without merging**
