### PR TITLE
Fix primary key duplication

### PR DESCRIPTION
**Pull request by jdangerx**
Relates to #2318 and #2294 - this is the primary key duplication fix mentioned.

Branched off of `dagster_xbrl_test_fix` so the xbrl stuff would be in.

But I think we should probably merge #2318 into `dagster-asset-etl` and then #2321 into `dagster-asset-etl`, and then we can merge this change into `dagster-asset-etl` as well.

When running the unit tests, I still get a ForeignKeyError, though:

```
=================================== FAILURES ===================================
________ [doctest] pudl.io_managers.SQLiteIOManager.check_foreign_keys _________
205
206         Examples:
207         This method can be used in the test suite or a jupyter notebook for debugging.
208
209             >>> from pudl.io_managers import pudl_sqlite_io_manager
210             >>> from dagster import build_init_resource_context
211             ...
212             >>> init_context = build_init_resource_context()
213             >>> manager = pudl_sqlite_io_manager(init_context)
214             >>> manager.check_foreign_keys()
UNEXPECTED EXCEPTION: ForeignKeyErrors([ForeignKeyError()])
Traceback (most recent call last):
  File "/Users/dazhong-catalyst/mambaforge/envs/pudl-dev/lib/python3.10/doctest.py", line 1350, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest pudl.io_managers.SQLiteIOManager.check_foreign_keys[4]>", line 1, in <module>
  File "/Users/dazhong-catalyst/work/pudl/src/pudl/io_managers.py", line 254, in check_foreign_keys
    raise ForeignKeyErrors(errors)
pudl.io_managers.ForeignKeyErrors: Foreign key error for table: cash_flow_ferc1 -- utilities_ferc1 (utility_id_ferc1) -- on rows [    1     2
   3 ... 23187 23188 23189]
/Users/dazhong-catalyst/work/pudl/src/pudl/io_managers.py:214: UnexpectedException
```

@bendnorman @zschira  do you know where the foreign key stuff is being defined? My next steps were going to be:
* [ ] slap a debugger in there
* [ ] try to see what's actually in the `cash_flow_ferc1` and `utilities_ferc1` tables

### CODE REVIEW

**Comment by bendnorman** [comment]
The foreign key information is stored in the `pudl.metadata.resources` sub-package.

**Comment by bendnorman** [comment]
@jdangerx how are you producing the FK error? A current issues with this dagster design is the database schema isn't updated if you have an existing database. The DB you using might have an out of date schema. I ran:

```
pytest test/integration/etl_test.py::test_pudl_engine
```

On this branch and I didn't get any FK errors.

**Comment by jdangerx** [comment]
Let me try that!

**Review by zschira — APPROVED** [review]
Getting so close!

**Comment by bendnorman** [comment]
Before we merge this in I think we should resolve the CI bug. The `pudl_sql_io_manager` fixture doesn't fail when there is a failure in the ETL.

**Comment by jdangerx** [comment]
Let's execute in process. Maybe the sales table bug goes in a different PR though so we can all be working off of `dev-dagster-merge-fixes` .

**Comment by zschira** [comment]
@bendnorman I think your idea to just use `execute_in_process` seems reasonable and probably the quickest solution. We could always just use `assert result.success` everywhere to catch errors, but this doesn't solve the logging problem. I would like to try and get the logging working with a parallel ETL, but we can probably leave that for future work.

**Comment by bendnorman** [comment]
@zschira totes agree.

I have the execute in process changes locally. Should we merge this branch in then open a new PR off of [dev-dagster-merge-fixes](https://github.com/catalyst-cooperative/pudl/tree/dev-dagster-merge-fixes) with the execute in process and sales table bug?

**Pull request merged**
