### PR TITLE
Simplified demand allocation algorithm

### PR DESCRIPTION
**Pull request by yashkumar1803**
1. Demand allocation algorithm simplified
2. Changed format structure of input and output dataframes
3. Change names of functions to `demand_allocation` and `compare_allocation`

### CODE REVIEW

**Comment by ezwelty** [comment]
@yashkumar1803 Here is an outline of a proposed core API for the geometric operations. Do not implement its components (some of them already are). Rather, could you try to express your current demand allocation pipeline following this API (pseudo-code is fine) and let me know what questions or concerns come up for you in the process?

Notes:
- The documentation and argument names are a mix of the GIS `layer`, `feature`, `attribute` terminology and the Python-implementation-specific `GeoDataFrame`, `row`, `column` terminology. Do you think this is confusing?
- I don't believe there is any need to specify an `id` attribute type, especially since there is always the DataFrame index and/or the row number. Tell me if you think otherwise.

```python
from typing import Callable, Dict, Union, Iterable, Literal

import geopandas as gpd
import pandas as pd
import shapely.geometry


def polygonize(
    geom: shapely.geometry.base.BaseGeometry, empty: bool = False
) -> Union[shapely.geometry.Polygon, shapely.geometry.MultiPolygon]:
    """
    Convert geometry to (Multi)Polygon.

    Args:
        geom: Geometry to convert to (Multi)Polygon.
        empty: Whether to return an empty Polygon (True) or raise an error (False).

    Returns:
        Geometry converted to (Multi)Polygon.
        Zero-area geometries of any type are removed from collections,
        and the remaining polygons converted to (Multi)Polygon.
        If `empty=True`, empty geometries are returned as an empty Polygon.

    Raises:
        ValueError: Geometry has zero area.
    """
    pass


def self_union(gdf: gpd.GeoDataFrame, ratios: Iterable[str] = None) -> gpd.GeoDataFrame:
    """
    Calculate the geometric union of a feature layer with itself.

    Areas of overlap are split into two or more geometrically-identical features:
    one for each of the original overlapping features.
    Each split feature contains the attributes of the original feature.

    Args:
        gdf: GeoDataFrame with non-empty (Multi)Polygon geometries.
        ratios: Names of columns to rescale by the area fraction of the split feature
            relative to the original. By default, the original value is used unchanged.

    Returns:
        GeoDataFrame representing the union of the input features with themselves.
        Its index contains tuples of the index of the original overlapping features.

    Raises:
        ValueError: Only (Multi)Polygon geometries are supported.
        ValueError: Empty Polygon geometries are not supported.
    """
    pass


def dissolve(
    gdf: gpd.GeoDataFrame,
    by: Iterable[str],
    func: Union[Callable, str, list, dict],
    how: Union[
        Literal["union", "first"],
        Callable[[gpd.GeoSeries], shapely.geometry.base.BaseGeometry],
    ] = "union",
) -> gpd.GeoDataFrame:
    """
    Dissolve layer by aggregating features based on common attributes.

    Args:
        gdf: GeoDataFrame with non-empty (Multi)Polygon geometries.
        by: Names of columns to group features by.
        func: Aggregation function for data columns (see :meth:`pd.DataFrame.groupby`).
        how: Aggregation function for geometry column.
            Either 'union' (:meth:`gpd.GeoSeries.unary_union`),
            'first' (first geometry in group),
            or a function aggregating multiple geometries into one.

    Returns:
        GeoDataFrame with dissolved geometry and data columns,
        and grouping columns set as the index.
    """
    pass


def overlay(
    *gdfs: gpd.GeoDataFrame,
    how: Literal[
        "intersection", "union", "identity", "symmetric_difference", "difference"
    ] = "intersection",
    ratios: Iterable[str] = None
) -> gpd.GeoDataFrame:
    """
    Overlay multiple layers incrementally.

    When a feature from one layer overlaps the feature of another layer,
    the area of overlap is split into two geometrically-identical features:
    one for each of the original overlapping features.
    Each split feature contains the attributes of the original feature.

    TODO: To identify the source of output features, the user can ensure that each
    layer contains a column to index by.
    Alternatively, tuples of indices of the overlapping
    feature from each layer (null if none) could be returned as the index.

    Args:
        gdfs: GeoDataFrames with non-empty (Multi)Polygon geometries
            assumed to contain no self-overlaps (see :func:`self_union`).
            Names of (non-geometry) columns cannot be used more than once.
            Any index colums are ignored.
        how: Spatial overlay method (see :func:`gpd.overlay`).
        ratios: Names of columns to rescale by the area fraction of the split feature
            relative to the original. By default, the original value is used unchanged.

    Raises:
        ValueError: Duplicate column names in layers.

    Returns:
        GeoDataFrame with the geometries and attributes resulting from the overlay.

    Examples:
        >>> from shapely.geometry import Polygon
        >>> import geopandas as gpd
        >>> gpd.options.precision = 0

        >>> a = gpd.GeoDataFrame({
        >>>     'geometry': gpd.GeoSeries([Polygon([(0, 0), (0, 1), (3, 1), (3, 0)])]),
        >>>     'a': [3.0]
        >>> })
        >>> b = gpd.GeoDataFrame({
        >>>     'geometry': gpd.GeoSeries([Polygon([(2, 0), (2, 1), (4, 1), (4, 0)])]),
        >>>     'b': [8.0]
        >>> })
        >>> overlay(a, b, how='intersection')
             a    b                             geometry
        0  3.0  8.0  POLYGON ((2 1, 3 1, 3 0, 2 0, 2 1))
        >>> overlay(a, b, how='union')
             a    b                             geometry
        0  3.0  8.0  POLYGON ((2 1, 3 1, 3 0, 2 0, 2 1))
        1  3.0  NaN  POLYGON ((0 0, 0 1, 2 1, 2 0, 0 0))
        2  NaN  8.0  POLYGON ((3 1, 4 1, 4 0, 3 0, 3 1))
        >>> overlay(a, b, how='union', ratios=['a', 'b'])
                                      geometry    a    b
        0  POLYGON ((2 1, 3 1, 3 0, 2 0, 2 1))  1.0  4.0
        1  POLYGON ((0 0, 0 1, 2 1, 2 0, 0 0))  2.0  NaN
        2  POLYGON ((3 1, 4 1, 4 0, 3 0, 3 1))  NaN  4.0
    """
    pass


class LayerBuilder:
    """
    Build a layer incrementally.

    Attributes:
        gdf (gpd.GeoDataFrame): GeoDataFrame with non-empty (Multi)Polygon geometries.
        ratios (List[str]): Names of columns (not necessarily present in `gdf`)
            to rescale by the area fraction of the split feature relative to the original.
            Has no effect on the geometry column.

    Raises:
        ValueError: Only non-empty (Multi)Polygon geometries are supported.
    """

    def __init__(self, gdf: gpd.GeoDataFrame, ratios: Iterable[str] = None) -> None:
        self.gdf = gdf
        self.ratios = ratios

    def join(
        self, df: pd.DataFrame, on: Iterable[str] = None, ratios: Iterable[str] = None
    ) -> None:
        """
        Join to table on common attributes.

        Args:
            df: Dataframe with attributes to add to the layer.
            on: Names of columns to join on.
                By default, joins on the column names common to both (ignoring geometry).
            ratios: Names of columns to rescale by the area fraction of the
                split feature relative to the original.

        Raises:
            ValueError: Table and layer have no column names in common.
            ValueError: Column names already exist.
            ValueError: Join columns missing from existing layer.
            ValueError: Ratio columns not present in table.
        """
        pass

    def sjoin(
        self,
        gdf: gpd.GeoDataFrame,
        how: Literal["left", "right", "inner"] = "left",
        op: Literal["intersects", "contains", "within"] = "intersects",
        ratios: Iterable[str] = None,
    ) -> None:
        """
        Join to layer on spatial binary predicate.

        Args:
            gdf: GeoDataFrame with non-empty (Multi)Polygon geometries.
            how: Type of join (see :func:`gpd.sjoin`).
            op: Binary predicate
                (http://shapely.readthedocs.io/en/latest/manual.html#binary-predicates).
            ratios: Names of columns to rescale by the area fraction of the
                split feature relative to the original.

        ValueError:
            ValueError: Column names already exist.
            ValueError: Ratio columns not present in layer.
            ValueError: Join results in non-empty (Multi)Polygon geometries.
        """
        pass

    def overlay(
        self,
        gdf: gpd.GeoDataFrame,
        how: Literal[
            "intersection", "union", "identity", "symmetric_difference", "difference"
        ] = "intersection",
        ratios: Iterable[str] = None,
    ) -> None:
        """
        Overlay onto layer.

        Args:
            gdf: GeoDataFrame with non-empty (Multi)Polygon geometries.
            ratios: Names of columns to rescale by the area fraction of the
                split feature relative to the original.

        ValueError:
            ValueError: Ratio columns not present in layer.
            ValueError: Only non-empty (Multi)Polygon geometries are supported.
        """
        pass

    def dissolve(
        self,
        by: Iterable[str],
        func: Union[Callable, str, list, dict],
        how: Union[
            Literal["union", "first"],
            Callable[[gpd.GeoSeries], shapely.geometry.base.BaseGeometry],
        ] = "union",
    ) -> gpd.GeoDataFrame:
        """
        Dissolve layer by aggregating features based on common attributes.

        See :func:`dissolve`. If `func=None`, ratio columns are summed and non-ratio
        columns are gathered into tuples.
        """
        pass
```

**Comment by yashkumar1803** [comment]
> @yashkumar1803 Here is an outline of a proposed core API for the geometric operations. Do not implement its components (some of them already are). Rather, could you try to express your current demand allocation pipeline following this API (pseudo-code is fine) and let me know what questions or concerns come up for you in the process?
> 
> Notes:
> 
> * The documentation and argument names are a mix of the GIS `layer`, `feature`, `attribute` terminology and the Python-implementation-specific `GeoDataFrame`, `row`, `column` terminology. Do you think this is confusing?
> * I don't believe there is any need to specify an `id` attribute type, especially since there is always the DataFrame index and/or the row number. Tell me if you think otherwise.
> 
> ```python
> from typing import Callable, Dict, Union, Iterable, Literal
> 
> import geopandas as gpd
> import pandas as pd
> import shapely.geometry
> 
> 
> def polygonize(
>     geom: shapely.geometry.base.BaseGeometry, empty: bool = False
> ) -> Union[shapely.geometry.Polygon, shapely.geometry.MultiPolygon]:
>     """
>     Convert geometry to (Multi)Polygon.
> 
>     Args:
>         geom: Geometry to convert to (Multi)Polygon.
>         empty: Whether to return an empty Polygon (True) or raise an error (False).
> 
>     Returns:
>         Geometry converted to (Multi)Polygon.
>         Zero-area geometries of any type are removed from collections,
>         and the remaining polygons converted to (Multi)Polygon.
>         If `empty=True`, empty geometries are returned as an empty Polygon.
> 
>     Raises:
>         ValueError: Geometry has zero area.
>     """
>     pass
> 
> 
> def self_union(gdf: gpd.GeoDataFrame, ratios: Iterable[str] = None) -> gpd.GeoDataFrame:
>     """
>     Calculate the geometric union of a feature layer with itself.
> 
>     Areas of overlap are split into two or more geometrically-identical features:
>     one for each of the original overlapping features.
>     Each split feature contains the attributes of the original feature.
> 
>     Args:
>         gdf: GeoDataFrame with non-empty (Multi)Polygon geometries.
>         ratios: Names of columns to rescale by the area fraction of the split feature
>             relative to the original. By default, the original value is used unchanged.
> 
>     Returns:
>         GeoDataFrame representing the union of the input features with themselves.
>         Its index contains tuples of the index of the original overlapping features.
> 
>     Raises:
>         ValueError: Only (Multi)Polygon geometries are supported.
>         ValueError: Empty Polygon geometries are not supported.
>     """
>     pass
> 
> 
> def dissolve(
>     gdf: gpd.GeoDataFrame,
>     by: Iterable[str],
>     func: Union[Callable, str, list, dict],
>     how: Union[
>         Literal["union", "first"],
>         Callable[[gpd.GeoSeries], shapely.geometry.base.BaseGeometry],
>     ] = "union",
> ) -> gpd.GeoDataFrame:
>     """
>     Dissolve layer by aggregating features based on common attributes.
> 
>     Args:
>         gdf: GeoDataFrame with non-empty (Multi)Polygon geometries.
>         by: Names of columns to group features by.
>         func: Aggregation function for data columns (see :meth:`pd.DataFrame.groupby`).
>         how: Aggregation function for geometry column.
>             Either 'union' (:meth:`gpd.GeoSeries.unary_union`),
>             'first' (first geometry in group),
>             or a function aggregating multiple geometries into one.
> 
>     Returns:
>         GeoDataFrame with dissolved geometry and data columns,
>         and grouping columns set as the index.
>     """
>     pass
> 
> 
> def overlay(
>     *gdfs: gpd.GeoDataFrame,
>     how: Literal[
>         "intersection", "union", "identity", "symmetric_difference", "difference"
>     ] = "intersection",
>     ratios: Iterable[str] = None
> ) -> gpd.GeoDataFrame:
>     """
>     Overlay multiple layers incrementally.
> 
>     When a feature from one layer overlaps the feature of another layer,
>     the area of overlap is split into two geometrically-identical features:
>     one for each of the original overlapping features.
>     Each split feature contains the attributes of the original feature.
> 
>     TODO: To identify the source of output features, the user can ensure that each
>     layer contains a column to index by.
>     Alternatively, tuples of indices of the overlapping
>     feature from each layer (null if none) could be returned as the index.
> 
>     Args:
>         gdfs: GeoDataFrames with non-empty (Multi)Polygon geometries
>             assumed to contain no self-overlaps (see :func:`self_union`).
>             Names of (non-geometry) columns cannot be used more than once.
>             Any index colums are ignored.
>         how: Spatial overlay method (see :func:`gpd.overlay`).
>         ratios: Names of columns to rescale by the area fraction of the split feature
>             relative to the original. By default, the original value is used unchanged.
> 
>     Raises:
>         ValueError: Duplicate column names in layers.
> 
>     Returns:
>         GeoDataFrame with the geometries and attributes resulting from the overlay.
> 
>     Examples:
>         >>> from shapely.geometry import Polygon
>         >>> import geopandas as gpd
>         >>> gpd.options.precision = 0
> 
>         >>> a = gpd.GeoDataFrame({
>         >>>     'geometry': gpd.GeoSeries([Polygon([(0, 0), (0, 1), (3, 1), (3, 0)])]),
>         >>>     'a': [3.0]
>         >>> })
>         >>> b = gpd.GeoDataFrame({
>         >>>     'geometry': gpd.GeoSeries([Polygon([(2, 0), (2, 1), (4, 1), (4, 0)])]),
>         >>>     'b': [8.0]
>         >>> })
>         >>> overlay(a, b, how='intersection')
>              a    b                             geometry
>         0  3.0  8.0  POLYGON ((2 1, 3 1, 3 0, 2 0, 2 1))
>         >>> overlay(a, b, how='union')
>              a    b                             geometry
>         0  3.0  8.0  POLYGON ((2 1, 3 1, 3 0, 2 0, 2 1))
>         1  3.0  NaN  POLYGON ((0 0, 0 1, 2 1, 2 0, 0 0))
>         2  NaN  8.0  POLYGON ((3 1, 4 1, 4 0, 3 0, 3 1))
>         >>> overlay(a, b, how='union', ratios=['a', 'b'])
>                                       geometry    a    b
>         0  POLYGON ((2 1, 3 1, 3 0, 2 0, 2 1))  1.0  4.0
>         1  POLYGON ((0 0, 0 1, 2 1, 2 0, 0 0))  2.0  NaN
>         2  POLYGON ((3 1, 4 1, 4 0, 3 0, 3 1))  NaN  4.0
>     """
>     pass
> 
> 
> class LayerBuilder:
>     """
>     Build a layer incrementally.
> 
>     Attributes:
>         gdf (gpd.GeoDataFrame): GeoDataFrame with non-empty (Multi)Polygon geometries.
>         ratios (List[str]): Names of columns (not necessarily present in `gdf`)
>             to rescale by the area fraction of the split feature relative to the original.
>             Has no effect on the geometry column.
> 
>     Raises:
>         ValueError: Only non-empty (Multi)Polygon geometries are supported.
>     """
> 
>     def __init__(self, gdf: gpd.GeoDataFrame, ratios: Iterable[str] = None) -> None:
>         self.gdf = gdf
>         self.ratios = ratios
> 
>     def join(
>         self, df: pd.DataFrame, on: Iterable[str] = None, ratios: Iterable[str] = None
>     ) -> None:
>         """
>         Join to table on common attributes.
> 
>         Args:
>             df: Dataframe with attributes to add to the layer.
>             on: Names of columns to join on.
>                 By default, joins on the column names common to both (ignoring geometry).
>             ratios: Names of columns to rescale by the area fraction of the
>                 split feature relative to the original.
> 
>         Raises:
>             ValueError: Table and layer have no column names in common.
>             ValueError: Column names already exist.
>             ValueError: Join columns missing from existing layer.
>             ValueError: Ratio columns not present in table.
>         """
>         pass
> 
>     def sjoin(
>         self,
>         gdf: gpd.GeoDataFrame,
>         how: Literal["left", "right", "inner"] = "left",
>         op: Literal["intersects", "contains", "within"] = "intersects",
>         ratios: Iterable[str] = None,
>     ) -> None:
>         """
>         Join to layer on spatial binary predicate.
> 
>         Args:
>             gdf: GeoDataFrame with non-empty (Multi)Polygon geometries.
>             how: Type of join (see :func:`gpd.sjoin`).
>             op: Binary predicate
>                 (http://shapely.readthedocs.io/en/latest/manual.html#binary-predicates).
>             ratios: Names of columns to rescale by the area fraction of the
>                 split feature relative to the original.
> 
>         ValueError:
>             ValueError: Column names already exist.
>             ValueError: Ratio columns not present in layer.
>             ValueError: Join results in non-empty (Multi)Polygon geometries.
>         """
>         pass
> 
>     def overlay(
>         self,
>         gdf: gpd.GeoDataFrame,
>         how: Literal[
>             "intersection", "union", "identity", "symmetric_difference", "difference"
>         ] = "intersection",
>         ratios: Iterable[str] = None,
>     ) -> None:
>         """
>         Overlay onto layer.
> 
>         Args:
>             gdf: GeoDataFrame with non-empty (Multi)Polygon geometries.
>             ratios: Names of columns to rescale by the area fraction of the
>                 split feature relative to the original.
> 
>         ValueError:
>             ValueError: Ratio columns not present in layer.
>             ValueError: Only non-empty (Multi)Polygon geometries are supported.
>         """
>         pass
> 
>     def dissolve(
>         self,
>         by: Iterable[str],
>         func: Union[Callable, str, list, dict],
>         how: Union[
>             Literal["union", "first"],
>             Callable[[gpd.GeoSeries], shapely.geometry.base.BaseGeometry],
>         ] = "union",
>     ) -> gpd.GeoDataFrame:
>         """
>         Dissolve layer by aggregating features based on common attributes.
> 
>         See :func:`dissolve`. If `func=None`, ratio columns are summed and non-ratio
>         columns are gathered into tuples.
>         """
>         pass
> ```

@ezwelty thanks for the new API structure. I have been going through the functions and had some trouble parsing the individual functions. I had a few questions and concerns:

* We would probably need functions to reconcile the time domain with the space domain e.g. a couple of helper functions that I had cleaned up geometries with no demand and service territories not linked to any geometries.
* Also, the `join` and the `sjoin` seem to work immediately on new dataframes that are added. The class LayerBuilder does not seem to store any dataframes or geodataframes. (I am not sure about this) It might be a good idea to keep a track of all the dataframes and geodataframes inside the layerbuilder.
* In the context of `attributes` i.e. uniform, constant and id, I am not able to figure out the equivalent here. Are ratios the equivalent to attributes?
* Another issue with the time domain is that some attributes (constant or uniform) can change from year to year. How could we possibly reconcile that?
* Also, is LayerBuilder enough, or are you considering creating another class that pulls from LayerBuilder for our specific purpose?
* There are two methods in LayerBuilder and which overlap outside of it as well i.e. dissolve and overlay. What is the difference between the class method and functions?

I will try to create the allocation based on my understanding of the API and get back to you.

**Comment by ezwelty** [comment]
@yashkumar1803 

> We would probably need functions to reconcile the time domain with the space domain e.g. a couple of helper functions that I had cleaned up geometries with no demand and service territories not linked to any geometries.

To me, this sounds like specialized pre-processing of the data layers particular to the demand allocation calculation as currently designed. I'm not expecting that what I drafted will cover every detail, but rather hope that it will cover the steps likely to be needed for other similar analysis. Where you find the API lacking, add a note explaining what is missing, perhaps with reference to where this is implemented in your current code.

> Also, the join and the sjoin seem to work immediately on new dataframes that are added. The class LayerBuilder does not seem to store any dataframes or geodataframes. (I am not sure about this) It might be a good idea to keep a track of all the dataframes and geodataframes inside the layerbuilder.

It does not, and for now, I see no problem with this. The input geodataframes are not modified in place. So they still exist outside the class, and can be held in memory as needed.

> In the context of attributes i.e. uniform, constant and id, I am not able to figure out the equivalent here. Are ratios the equivalent to attributes?

I argue that the `id` attribute type is an unnecessary complication, and constant attributes are the default when splitting features. So I simplified it to just specifying when a split feature takes on the ratio of the original value with respect to area. I realized that "uniform" would probably be confusing in the long term. The name "ratio" is inspired by ArcGIS' split policies: https://pro.arcgis.com/en/pro-app/help/data/geodatabases/overview/an-overview-of-attribute-domains.htm.

> Another issue with the time domain is that some attributes (constant or uniform) can change from year to year. How could we possibly reconcile that?

When trying to write out the calculation based on the new API, do so for just one year, then point out what steps need to be repeated for each year, and which computational results can be reused from year to year.

> Also, is LayerBuilder enough, or are you considering creating another class that pulls from LayerBuilder for our specific purpose?

Let's see how the outline looks, and check with Zane. If it seems like the specific steps are likely to change to adapt to different calculations of demand, different data layers, etc, it may well not be worth bundling those steps into a class.

> There are two methods in LayerBuilder and which overlap outside of it as well i.e. dissolve and overlay. What is the difference between the class method and functions?

`self_union` may be used as an optional step when preparing a feature layer before use with `LayerBuilder`. `overlay` is another standalone function which is wrapped by the method `LayerBuilder.overlay` as a convenience to users.

Feel free to reach out with more questions.

**Comment by yashkumar1803** [comment]
> @yashkumar1803
> 
> > We would probably need functions to reconcile the time domain with the space domain e.g. a couple of helper functions that I had cleaned up geometries with no demand and service territories not linked to any geometries.
> 
> To me, this sounds like specialized pre-processing of the data layers particular to the demand allocation calculation as currently designed. I'm not expecting that what I drafted will cover every detail, but rather hope that it will cover the steps likely to be needed for other similar analysis. Where you find the API lacking, add a note explaining what is missing, perhaps with reference to where this is implemented in your current code.
> 
> > Also, the join and the sjoin seem to work immediately on new dataframes that are added. The class LayerBuilder does not seem to store any dataframes or geodataframes. (I am not sure about this) It might be a good idea to keep a track of all the dataframes and geodataframes inside the layerbuilder.
> 
> It does not, and for now, I see no problem with this. The input geodataframes are not modified in place. So they still exist outside the class, and can be held in memory as needed.
> 
> > In the context of attributes i.e. uniform, constant and id, I am not able to figure out the equivalent here. Are ratios the equivalent to attributes?
> 
> I argue that the `id` attribute type is an unnecessary complication, and constant attributes are the default when splitting features. So I simplified it to just specifying when a split feature takes on the ratio of the original value with respect to area. I realized that "uniform" would probably be confusing in the long term. The name "ratio" is inspired by ArcGIS' split policies: https://pro.arcgis.com/en/pro-app/help/data/geodatabases/overview/an-overview-of-attribute-domains.htm.
> 
> > Another issue with the time domain is that some attributes (constant or uniform) can change from year to year. How could we possibly reconcile that?
> 
> When trying to write out the calculation based on the new API, do so for just one year, then point out what steps need to be repeated for each year, and which computational results can be reused from year to year.
> 
> > Also, is LayerBuilder enough, or are you considering creating another class that pulls from LayerBuilder for our specific purpose?
> 
> Let's see how the outline looks, and check with Zane. If it seems like the specific steps are likely to change to adapt to different calculations of demand, different data layers, etc, it may well not be worth bundling those steps into a class.
> 
> > There are two methods in LayerBuilder and which overlap outside of it as well i.e. dissolve and overlay. What is the difference between the class method and functions?
> 
> `self_union` may be used as an optional step when preparing a feature layer before use with `LayerBuilder`. `overlay` is another standalone function which is wrapped by the method `LayerBuilder.overlay` as a convenience to users.
> 
> Feel free to reach out with more questions.

START

years = range(2011, 2014)
for year in years:
    
    demand_layer = LayerBuilder(ba_county_map, some of ba_county_map.columns)
    demand_layer.join(county_gdf, on="county_id_fips", ratios=["population"])
    
    ## ratios divided amongst multiple regions with same timestamp
    ## also drop all service territories without geometry
    demand_layer.join(pa_demand_df, on="county_id_fips")
    
    1x SELECT one year data at a time OR at 2x
    
    demand_layer.overlay(reeds_gdf, "intersection") ## ratios distributed amongst added layer
    
    2x SELECT one year data at a time OR at 1x
    
    demand_layer.allocate(allocate="demand_mwh", groupby=["respondent_ferc714", "utc_datetime"],
                          allocators={"population":1})
    
    demand_layer.dissolve(["pca", "utc_datetime"])

**Comment by ezwelty** [comment]
@yashkumar1803 @zaneselvans

Say we have these tables with the following fields. Each table is either constant in the modeling of demand, or varies on different time periods.

- `outputs` (constant): [`geometry`, `output_id`] – Output geometries for demand allocation.
- `counties` (decade): [`geometry`, `county_id`, `population`] – U.S. counties and their census population.
- `county_assignments` (year): [`county_id`, `demand_id`] – Pre-computed assignment of counties to the demand areas.
- `demands` (hour): [`demand_id`, `year`, `hour`, `mwh`] - Input demand by area (`demand_id`), year, and hour. 

Allocating demand by fractional population with the proposed API might look like the following, with steps performed in the order in which they are needed.

```python
### For all years
# Start with counties
# [ geometry | county_id | population ]
self = LayerBuilder(counties)
# Overlay output geometries
# + [ *geometry, output_id ]
self.overlay(outputs, ratios=['population'], how='intersection')

### For each year
# Add pre-computed county-demand spatial assignments
# + [ *county_id | demand_id ]
self.join(county_assignments)

### For each hour
# Add demand timeseries
# + [ *demand_id | year | hour | mwh ]
self.join(demands)
# Scale county demand proportional to total demand area population
self.gdf['mwh'] *= (
    self.gdf['population'] / 
    self.gdf.groupby(['demand_id'])['population'].transform('sum')
)
# Sum county demand by demand area and timestamp
# = [ geometry | output_id | year | hour | mwh ]
self.dissolve(by=['output_id', 'year', 'hour'], how='union', func={'mwh': 'sum'})
```

Note that some groupby-aggregate calculations are performed on a larger join of the data – and columns are kept longer – than is strictly necessary. If needed, better memory and cpu performance can be achieved with something like this, where here it honestly seems more transparent to use geopandas, pandas, and the standalone API functions directly (rather than `LayerBuilder`).

```python
### For all years
# Compute county-output overlay
# [ output_id | county_id | population ]
overlay_df = (
    overlay(outputs, counties, ratios=['population'], how='intersection')
    .drop(columns='geometry')
)

### For each year (demand.geometry)
# Compute demand area population
# [ county_id | demand_id | demand_population ]
demand_func = lambda x: x.groupby(['demand_id'])['population'].transform('sum')
demand_df = (
    counties[['county_id', 'population']]
    .merge(county_assignments, on="county_id")
    .assign(demand_population=demand_func)
    .drop(columns='population')
)
# Merge with county-output overlay to compute fractional population
# [ output_id | demand_id | population_fraction ]
demand_fraction_df = (
    overlay_df
    .merge(demand_df, on="county_id")
    .assign(population_fraction=lambda x: x['population'] / x['demand_population'])
    .drop(columns=['county_id', 'population', 'demand_population'])
)

### For each hour (demand.hour)
# Merge with demand timeseries, scale demand, and aggregate for output
(
    demand_fraction_df
    .merge(demand, on='demand_id')
    .assign(mwh = lambda x: x['mwh'] * x['population_fraction'])
    .groupby(by=['output_id', 'year', 'hour'])
    .agg({'mwh': 'sum'})
)
```

**Comment by ezwelty** [comment]
@yashkumar1803 I should add that the API functions I use in my first version are implemented. Both versions in my previous comment run on your test example and produce the same result as your current code. Does it seem to you like it is doing the same computation as your current code?

**Comment by ezwelty** [comment]
@yashkumar1803 I just pushed it to this branch, as `pudl/analysis/spatial.py`. Watch out for column names in my two examples – they probably differ from the column names in the original datasets. Feel free to reach out quickly if you run into issues. Happy to debug running a more complete test, but will want to make sure we are both running the same test.

p.s. Here are some notes that I took when originally reviewing your code and examples. Less relevant as specific instructions, since a lot of the code will be changing, but more as general feedback. Hopefully it is helpful.

- Remove `else`, `elif` statements made unnecessary by `return` or `raise` statements.
- Replace blocks of `del` statements with a single `pd.DataFrame.drop` or `df[]`.
- Do not include unused imports or irrelevant code in examples. They make the example longer, less transparent, and less likely to complete successfully on someone else's machine.
- Set a default argument value before assigning to a class variable (e.g. `if x is None: x = 1; self.x = x`, not `if x is None: self.x = 1; else: self.x = x`)
- Ensure all allowed conditions yield valid code (e.g. `if x: z = 1; if y: z += 1` breaks if `x` is false and `y` is true)
- Remove empty `return` statements. That is the default.

**Comment by ezwelty** [comment]
@zaneselvans

I added a new module: `pudl.analysis.state_demand.py`. It includes functions that prepare FERC 714 hourly demand for analysis (formatting, anomaly detection, imputation, filtering), functions that load demand allocation datasets, and finally functions that perform state-level allocation and generate various outputs. As we have discussed, the results are strongly dependent on the FERC 714 county assignments inferred by `pudl.output.ferc714.Respondents`, which are unreliable. A `main` script runs an example complete pipeline.

Things to consider for your review:

- I created a few general constants and helper functions pertaining to US States and timezones. Should these be moved elsewhere?
- Should the `main` script support command-line arguments, and if so, which ones?
- I did not include any code for exploring issues with the FERC 714 county assignments. My method amounted to inspecting the unscaled demand in the state-level timeseries plots, identifying big jumps between years, then looking for the cause of the jump in annual respondent per-capita or per-area demand (see `pudl.output.ferc714.Respondents.summarize_demand()`).
- Why are `pudl_settings`, `pudl_out`, ... variables passed around as arguments to functions, rather than accessed directly via `pudl.workspace.setup.get_defaults()`, ...? Having a single location for these could really simplify the codebase, documentation, and the development of more complex workspace features, like caching:
- I did not include any caching to disk for the slower steps. It is very difficult to determine automatically when to deprecate the cache in these contexts. However, a basic cache (does not consider function arguments) that can be cleared manually could look like this.

```python
import logging
import pathlib
import pickle
from typing import Any, Callable

import pudl

LOGGER = logging.getLogger(__name__)

CACHE_DIR = pathlib.Path(pudl.workspace.setup.get_defaults()['data_dir']) / 'cache'


def cache() -> Callable:
    def decorator(fn: Callable) -> Callable:
        path = CACHE_DIR / f'{fn.__module__}.{fn.__name__}.pkl'
        # Define a wrapper to call decorated function
        def wrapped(*args: Any, **kwargs: Any) -> Any:
            # If cache exists, load and return
            if path.exists():
                LOGGER.info(f'{fn.__name__}: Reading cache from {path}')
                return pickle.load(open(path, 'rb'))
            # Execute the decorated function
            result = fn(*args, **kwargs)
            # Write result to file
            LOGGER.info(f'{fn.__name__}: Caching result to {path}')
            path.parent.mkdir(parents=True, exist_ok=True)
            pickle.dump(result, open(path, 'wb'))
            return result
        wrapped.cache_path = path
        wrapped.cache_clear = lambda: path.unlink(missing_ok=True)
        wrapped.__wrapped__ = fn
        return wrapped
    return decorator


@cache()
def f():
    return 1
```

Modules in review

- `pudl.analysis.state_demand.py`: Prepares FERC 714 hourly demand for analysis and predicts state-level demand. No spatial operations are used because FERC 714 respondent service territories are mapped to whole counties and only county-level attributes (i.e. population) are used.
- `pudl.analysis.spatial.py`: [unused] Collection of generalized spatial operations. In retrospect `LayerBuilder` is probably not worth the added abstraction, but the standalone functions (most notably, `overlay()`) would be useful for allocating demand to geometries that do not map to whole counties (see below).
- `pudl.analysis.demand_mapping.py`: [unused, largely deprecated] Yash's original demand allocation module.

Example of demand allocation using `pudl.analysis.spatial.overlay()`:

```python
### For all years (counties, outputs)

# Population of each (overlayed) county
# output_id | county_id | population
overlay_df = (
    overlay(outputs, counties, ratios=['population'], how='intersection')
    .drop(columns='geometry')
)

## For each year (county_assignments)

# Total county population in each demand area
# demand_id | demand_population
demand_df = (
    counties[['county_id', 'population']]
    .merge(county_assignments, on="county_id")
    .groupby('demand_id', as_index=False)
    .aggregate({'population': 'sum'})
    .rename(columns={'population': 'demand_population'})
)

# Fraction of demand population for each (overlayed) county
# output_id | demand_id | county_id | demand_population_fraction
demand_fraction_df = (
    overlay_df
    .merge(county_assignments, on="county_id")
    .merge(demand_df, on="demand_id")
    .assign(demand_population_fraction=lambda x: x['population'] / x['demand_population'])
    .drop(columns=['population', 'demand_population'])
)

### For each hour (demands)

# Merge with demand timeseries, scale demand, and aggregate for output
result_df = (
    demand_fraction_df
    .merge(demands, on='demand_id')
    .assign(mwh = lambda x: x['mwh'] * x['demand_population_fraction'])
    # Sum all county segments overlaying each output geometry
    .groupby(['output_id', 'utc_datetime'], as_index=False)
    .aggregate({'mwh': 'sum'})
)
```

**Comment by zaneselvans** [comment]
@ezwelty Am I right that the `demand_mapping.py` module has been superseded by what's in the `spatial.py` module? And that the two notebooks which are in this PR don't relate to the current version of the code?

**Comment by ezwelty** [comment]
> @ezwelty Am I right that the `demand_mapping.py` module has been superseded by what's in the `spatial.py` module? And that the two notebooks which are in this PR don't relate to the current version of the code?

Yes, the two notebooks and `demand_mapping.py` are essentially deprecated. 
The entirety of `spatial.LayerBuilder` could also be removed (I no longer see it as a useful abstraction).
The remaining `spatial` functions could be useful in the future, especially `overlay`, which is all that would be needed to modify the calculation in `state_demand` to work with arbitrary geometries.

**Pull request merged**
