### PR TITLE
Add pudl id mapping rst docs

### PR DESCRIPTION
**Pull request by aesharpe**
### This PR: 

* Changes the name of the mapping spreadsheet from `mapping_eia923_ferc1.xlsx` to `pudl_id_mapping.xlsx`. It also removes extraneous tabs from the spreadsheet so there are only two: one for utility mapping and one for plant mapping.

* Add columns to `pudl_id_mapping.xlsx` utility tab to identify utilities that have shown up before (using `utility_id_ferc1` and `utility_id_eia` record identification).

* Adds an RST file to the Development docs tree explaining the PUDL ID mapping process.

* Makes sure the `find_unmapped_plants_utils.py` script outputs to the `devtools/ferc1-eia-glue` directory.

* Fixes miss-matched utility_id_ferc values (1 and 400) in the `pudl_id_mapping.xlsx` sheet. 

### Review TO DO:
- [x] Read through the docs and make sure it all looks good/makes sense.

### Code TO DO: 
- [ ] Using the new columns in the plant_id_pudl mapping sheet utility tab, update utility ids. This might have to be a new issue.
- [x] Learn more about the utility mapping process and the different tabs. Currently, the tests are failing because they are finding a few unmapped utilities because I pointed it at a different tab on the mapping spreadsheet.
- [x] Add more detail in the utility id mapping section. How to you get the utilities from the unmapped spreadsheets into the mapping spreadsheet? Are there any caveats or formulas you have to pay attention to? Do you have to manually assign `utility_id_pudl`?

### CODE REVIEW

**Review by cmgosnell — APPROVED** [review]
These changes all look good! The the [new page](url) on readthecos look good to me. I think it all generally understandable. It may be good to get someone who is not 100% familiar with this process to read this over, but I think this is certainly good enough for now!

**Review by cmgosnell — CHANGES_REQUESTED** [review]
It looks like there are some failures happening in `test_unmapped_utils_ferc1` maybe because of the file name change?

**Comment by aesharpe** [comment]
> It looks like there are some failures happening in `test_unmapped_utils_ferc1` maybe because of the file name change?
> 
> It looks like you also haven't deleted some of the extra tabs in the file. I know you were thinking about that so idk if it isn't just checked in or what.

I think it might actually be because there are two new unmapped utilities?! I don't know where those guys came from....

**Review by bendnorman — APPROVED** [review]
Looks good to me, thanks for writing this up! Only comment is you could link the mapping documentation in the [Annual Updates: Integration between datasets](https://catalystcoop-pudl--1387.org.readthedocs.build/en/1387/dev/annual_updates.html#integration-between-datasets) section.

**Review by TrentonBush — APPROVED** [review]
This seems pretty comprehensive to me. Looks ready to go!

**Pull request merged**
