### PR TITLE
If branch is a fork, skip the `release.yml` workflow

### PR DESCRIPTION
**Pull request by e-belfer**
# Overview

What problem does this address?
Our `release.yml` workflow can't be run on forks without us taking over the PR (see #3670 for latest problems). This test doesn't often fail, and is typically only critical for release PRs, which we don't anticipate being external PRs. So, let's disable this test for PRs on forks.

What did you change?
Added an `if:` conditional to the first job, that checks whether it is a fork. The other jobs depend on the first, so if it is skipped the rest of the jobs will also be skipped.

# Testing

How did you make sure this worked? How can a reviewer verify this?
Check the test still runs on this branch. Once it's merged, open a fork and see if the check still attempts to run?

```[tasklist]
# To-do list
- [x] Review the PR yourself and call out any questions or issues you have
```

### CODE REVIEW

**Review by zaneselvans — COMMENTED** [review]
Does skipping all of the jobs in the workflow count as "passing" in the context of a required check? I tried making a similar change on the FERC-714 PR (both on the PR branch and on main) and it didn't have the outcome I expected.

How can we most easily test that this does what we want? I imagine it needs to be on both `main` and the branch/fork that the PR is coming from, and then we'll need to make the `release` workflow a required check again and make a PR from a fork on a personal account.

**Comment by e-belfer** [comment]
> Does skipping all of the jobs in the workflow count as "passing" in the context of a required check? I tried making a similar change on the FERC-714 PR (both on the PR branch and on main) and it didn't have the outcome I expected.

Tested by making the repository wrong here, and yes, this works as expected!

**Review by zaneselvans — APPROVED** [review]

**Comment by zaneselvans** [comment]
Should I re-enable the `release` check as required now? It seems like we expect it to skip and have that be okay.

**Comment by zaneselvans** [comment]
I've set the package build back to being required.

**Comment by e-belfer** [comment]
[Based on this documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks) I think that should work.

**Pull request merged**
