### PR TITLE
Fix build error for `epacamd_eia_test`

### PR DESCRIPTION
**Pull request by aesharpe**
```
FAILED test/validate/eia_test.py::test_minmax_rows[eia_raw-plants_eia860-185071-185071-185071]
FAILED test/validate/eia_test.py::test_minmax_rows[eia_raw-pu_eia860-184260-184260-184260]
FAILED test/validate/eia_test.py::test_minmax_rows[eia_raw-utils_eia860-119158-119158-119158]
FAILED test/validate/epacamd_eia_test.py::test_unique_ids[eia_raw] - Attribut...
FAILED test/validate/eia_test.py::test_minmax_rows[eia_annual-plants_eia860-185071-185071-185071]
FAILED test/validate/eia_test.py::test_minmax_rows[eia_annual-pu_eia860-184260-184260-184260]
FAILED test/validate/eia_test.py::test_minmax_rows[eia_annual-utils_eia860-119158-119158-119158]
FAILED test/validate/epacamd_eia_test.py::test_unique_ids[eia_annual] - Attri...
FAILED test/validate/eia_test.py::test_minmax_rows[eia_monthly-plants_eia860-185071-185071-185071]
FAILED test/validate/eia_test.py::test_minmax_rows[eia_monthly-pu_eia860-184260-184260-184260]
FAILED test/validate/eia_test.py::test_minmax_rows[eia_monthly-utils_eia860-119158-119158-119158]
FAILED test/validate/epacamd_eia_test.py::test_unique_ids[eia_monthly] - Attr...
= 12 failed, 469 passed, 120 skipped, 15 xfailed, 2 xpassed, 29 warnings in 9422.54s (2:37:02) =

```

### CODE REVIEW

**Review by zaneselvans — APPROVED** [review]

**Comment by zaneselvans** [comment]
Re: the FK errors. I think if the harvesting sees `(plant_id_eia, boiler_id)` in the columns, then it will try and harvest the values it sees in those columns for inclusion in the boiler entity table, and it will also assume that there should be an FK relationship between those columns and the boiler table, which is correct. I'd think it would ignore NA values in both of those cases, but maybe it doesn't? It seems like this would have come up in other tables too.

If necessary you can tell it to ignore some of the automatically generated FK relationships in the resource (table) definition.

**Comment by aesharpe** [comment]
Fixed the validation test for `test/validate/epacamd_eia_test.py`

**Comment by aesharpe** [comment]
Now the issue is the min-max row tests. 

I looked at the EIA annual plants 860 table which was one of the tables that failed. It appears that the table resulting from the failed build has **two less rows** than the table resulting from the successful build (Sept 15th).

The rows that show up in the _working_ build table are:
* `2022-01-01 | 62844 | Cranberry Point Energy Storage`
* `2022-01-01 | 64835 | Silver Queen Wind Farm`

I did some more digging and found out that beyond missing rows, there are 7946 rows that differ between the two tables. I looked at an example (`2022-01-01 | 195`) and see that the only difference is in the `plant_name_eia` field. The working build table says `Narrows (AR)` and the failed build table says `Narrows`. 

Because the failed build actually has _fewer_ rows than the working build, I don' think this is a harvesting issue. I'm also pretty sure that the harvesting happens before the glue tables are ever processed. 





`

**Comment by aesharpe** [comment]
> Re: the FK errors. I think if the harvesting sees `(plant_id_eia, boiler_id)` in the columns, then it will try and harvest the values it sees in those columns for inclusion in the boiler entity table, and it will also assume that there should be an FK relationship between those columns and the boiler table, which is correct. I'd think it would ignore NA values in both of those cases, but maybe it doesn't? It seems like this would have come up in other tables too.
> 
> If necessary you can tell it to ignore some of the automatically generated FK relationships in the resource (table) definition.

Foreign key problems were related to my local errors

**Comment by aesharpe** [comment]
The only thing done to `dev` between the 15th and the fail was some documentation updates and, and the re-addition of the `epacamd_eia` analysis module used by Greg. There is no output table attached to the analysis module, it's just some useful functions to restructure the crosswalk and calculate sub-plants. 

Screen Shot 2022-09-20 at 5 30 12 PM

**Comment by zaneselvans** [comment]
The ~8000 rows that are different maybe that could just be a small number of plants for which the most common plant name changed due to values that were harvested from the crosswalk?

Also `plant_name_eia` should be in the `plants_entity_eia` table, not the `plants_eia860` table. What differences do you see between those two tables (not using the output functions)

**Comment by aesharpe** [comment]
> The ~8000 rows that are different maybe that could just be a small number of plants for which the most common plant name changed due to values that were harvested from the crosswalk?

If I'm not mistaken, the harvesting process is outlined in the `eia.py` transform module which gets called in the `_etl_eia()` function in the `etl.py` module which happens before (and therefore seperate from) `_etl_glue()` which processes the crosswalk table.

from the `etl()` function in `etl.py`
```
    if datasets.get("ferc1", False):
        sqlite_dfs.update(_etl_ferc1(datasets["ferc1"], pudl_settings))
    if datasets.get("eia", False):
        sqlite_dfs.update(_etl_eia(datasets["eia"], ds_kwargs))
    if datasets.get("glue", False):
        sqlite_dfs.update(
            _etl_glue(datasets["glue"], ds_kwargs, sqlite_dfs, datasets["eia"])
        )
```

**Comment by zaneselvans** [comment]
The build outputs from Sept. 15th would have reflected anything that got merged into `dev` on September 14th (that was successful).

If the first failed build was the one that happened the night of Sept. 15/16th, that would have been from anything merged into `dev` on Sept. 15th.  So what happened on the 15th?

**Comment by aesharpe** [comment]
> If the first failed build was the one that happened the night of Sept. 15/16th, that would have been from anything merged into `dev` on Sept. 15th. So what happened on the 15th?

I thought the last successful build was from the 15th? Does that mean morning of the 15ths?

**Comment by zaneselvans** [comment]
The last successful build outputs have a date of September 15th. The builds start at 1am and typically run until 5-6am, Mountain time, or 12-1pm UTC, which is what the GCP dates are in:

```
 843649024  2022-09-15T12:27:02Z  gs://intake.catalyst.coop/dev/censusdp1tract.sqlite
 761257984  2022-09-15T12:27:04Z  gs://intake.catalyst.coop/dev/ferc1.sqlite
5110330869  2022-09-15T12:28:59Z  gs://intake.catalyst.coop/dev/hourly_emissions_epacems.parquet
 702459904  2022-09-15T12:27:01Z  gs://intake.catalyst.coop/dev/pudl.sqlite
```

**Comment by aesharpe** [comment]
> Also `plant_name_eia` should be in the `plants_entity_eia` table, not the `plants_eia860` table. What differences do you see between those two tables (not using the output functions)

Ok I tried the same thing but with the the plants_eia860 table from the db (not the output tables) and the tables are the same....

**Comment by zaneselvans** [comment]
> Ok I tried the same thing but with the the plants_eia860 table from the db (not the output tables) and the tables are the same....

You said what was different was `plant_name_eia` and that field is in `plants_entity_eia` so that is the table to compare between the two DBs if you're looking for plant name discrepancies

This command (executed with `dev` checked out) will show all the commits that came into `dev` on 2022-09-15 -- it's just the crosswalk PR.
```
git log --first-parent --since 2022-09-14 --until 2022-09-15
```

**Comment by aesharpe** [comment]
> So what happened on the 15th?

I updated the screenshot above to show the commits from the 15th

**Comment by aesharpe** [comment]
> --since 2022-09-14 --until 2022-09-15

Wouldn't that be the 14th?

**Comment by zaneselvans** [comment]
Nope. I just ran it.

**Comment by aesharpe** [comment]
> You said what was different was `plant_name_eia` and that field is in `plants_entity_eia` so that is the table to compare between the two DBs if you're looking for plant name discrepancies

Those tables are also the same.

**Comment by zaneselvans** [comment]
Okay so if you compare pre & post failure `pudl_out.plants_eia860()` dataframes you find differences in `plant_name_eia`

But if you compare pre and post failure `plants_entity_eia` tables straight from the database, you find that they are identical?

**Comment by aesharpe** [comment]
> * 64835

**Comment by aesharpe** [comment]
Neither of the missing plant_id_eia rows `64835 , 62844` are in the crosswalk either.

**Comment by zaneselvans** [comment]
So the only thing that you're concerned about now is understanding why the addition of the `epacamd_eia` crosswalk table seems to have affected the contents of the `plants_eia860` table?

**Comment by aesharpe** [comment]
> So the only thing that you're concerned about now is understanding why the addition of the `epacamd_eia` crosswalk table seems to have affected the contents of the `plants_eia860` table?

That was just one example, there were other EIA tables that were affected (failed)

**Comment by zaneselvans** [comment]
Okay so in general the concern is that adding the crosswalk table seems to have affected other EIA tables, and that seems weird / wrong?

**Comment by zaneselvans** [comment]
Can you diff all of the tables between these two databases you have and identify the differences?

**Comment by zaneselvans** [comment]
#1692 did modify more than 30 files so... it does seem like there could be some impacts in there. I will look over the changes.

**Comment by aesharpe** [comment]
Here's a record of the differences for the plants_eia860 table from the db:

* `plant_id_eia`: 10012 | `report_year`: 2002 & 2001--> `ferc_cogen_status` goes from `FALSE` to `None`
* `plant_id_eia`: 10012 | `report_year`: 2002 & 2001--> `ferc_exempt_wholesale_generator` goes from `FALSE` to `None`
* `plant_id_eia`: 10012 | `report_year`: 2002 & 2001--> `ferc_small_power_producer_docket_no` goes from `86-501-000` to `None`
* `plant_id_eia`: 10012 | `report_year`: 2002 & 2001--> `ferc_small_power_producer ` goes from `TRUE` to `None`
* `plant_id_eia`: 7549 | `report_year`: 2002 & 2001--> `ferc_cogen_status` goes from `FALSE` to `None`
* `plant_id_eia`: 7549 | `report_year`: 2002 & 2001--> `ferc_exempt_wholesale_generator` goes from `FALSE` to `None`
* `plant_id_eia`: 7549 | `report_year`: 2002 & 2001--> `ferc_small_power_producer ` goes from `FALSE` to `None` 
*

**Comment by zaneselvans** [comment]
Looking back over the PR, the only thing that seems like it might have effects all over the EIA data is the re-write of the leading-zero fixer function. It does **look** like the new function should be doing the same thing as the old function, but it's notoriously easy to mess up regular expressions.

What is the extent of the differences between the two builds? If it's just a couple of extra rows, or a half dozen individual fields for a couple of random plants 20 years ago, then that doesn't seem scary and we should probably just update the expected number of records.

If there are thousands of rows in multiple tables where the contents have changed as you said above, that seems more concerning. Is that really happening?

**Comment by aesharpe** [comment]
I adjusted the row count to account for the -2 rows in each of the `pu_eia860`, `plants_eia860`, and `utils_eia860` tables. I still don't know _why_ this is happening. 

In case we want to revisit this later (and maybe add some regression analysis), I took stock of the types of columns that are changing in the `plants_eia860` output table.

There are 2 fewer rows in the current table (than in the version before adding the epacamd_eia crosswalk from PR #1692). There are also 3974 rows (out of 185071 or 185069 rows--depending on whether you compare the old or new version) that differ between the two tables. 

The following table shows, for the `plants_eia860` output table, what column data has changed. It compares the 3974 rows that differ between the tables to see which columns (represented as the index here) are the culprits.
- `count` shows the total number of rows
- `unique` shows the column contains disperate data (1=no, 2=yes)
- `freq` shows the number of times that column values from miss-matched rows are the same
- `pct` shows the percent of times this column is responsible for the discrepancy between rows in the two versions of the output table

|                                              |   count |   unique |   freq |        pct |
|:---------------------------------------------|--------:|---------:|-------:|-----------:|
| plant_name_eia                               |    3974 |        2 |   2981 | 24.9874    |
| city                                         |    3974 |        1 |   3974 |  0         |
| county                                       |    3974 |        1 |   3974 |  0         |
| latitude                                     |    3974 |        1 |   3974 |  0         |
| longitude                                    |    3974 |        2 |   2975 | 25.1384    |
| state                                        |    3974 |        1 |   3974 |  0         |
| street_address                               |    3974 |        1 |   3974 |  0         |
| zip_code                                     |    3974 |        1 |   3974 |  0         |
| timezone                                     |    3974 |        2 |   3879 |  2.39054   |
| ash_impoundment                              |    3974 |        1 |   3974 |  0         |
| ash_impoundment_lined                        |    3974 |        1 |   3974 |  0         |
| ash_impoundment_status                       |    3974 |        1 |   3974 |  0         |
| balancing_authority_code_eia                 |    3974 |        1 |   3974 |  0         |
| balancing_authority_name_eia                 |    3974 |        1 |   3974 |  0         |
| datum                                        |    3974 |        1 |   3974 |  0         |
| energy_storage                               |    3974 |        1 |   3974 |  0         |
| ferc_cogen_docket_no                         |    3974 |        1 |   3974 |  0         |
| ferc_cogen_status                            |    3974 |        2 |   3970 |  0.100654  |
| ferc_exempt_wholesale_generator_docket_no    |    3974 |        1 |   3974 |  0         |
| ferc_exempt_wholesale_generator              |    3974 |        2 |   3970 |  0.100654  |
| ferc_small_power_producer_docket_no          |    3974 |        2 |   3972 |  0.0503271 |
| ferc_small_power_producer                    |    3974 |        2 |   3970 |  0.100654  |
| ferc_qualifying_facility_docket_no           |    3974 |        1 |   3974 |  0         |
| grid_voltage_1_kv                            |    3974 |        1 |   3974 |  0         |
| grid_voltage_2_kv                            |    3974 |        1 |   3974 |  0         |
| grid_voltage_3_kv                            |    3974 |        1 |   3974 |  0         |
| iso_rto_code                                 |    3974 |        1 |   3974 |  0         |
| liquefied_natural_gas_storage                |    3974 |        1 |   3974 |  0         |
| natural_gas_local_distribution_company       |    3974 |        1 |   3974 |  0         |
| natural_gas_storage                          |    3974 |        1 |   3974 |  0         |
| natural_gas_pipeline_name_1                  |    3974 |        1 |   3974 |  0         |
| natural_gas_pipeline_name_2                  |    3974 |        1 |   3974 |  0         |
| natural_gas_pipeline_name_3                  |    3974 |        1 |   3974 |  0         |
| nerc_region                                  |    3974 |        1 |   3974 |  0         |
| net_metering                                 |    3974 |        1 |   3974 |  0         |
| pipeline_notes                               |    3974 |        1 |   3974 |  0         |
| primary_purpose_id_naics                     |    3974 |        1 |   3974 |  0         |
| regulatory_status_code                       |    3974 |        1 |   3974 |  0         |
| reporting_frequency_code                     |    3974 |        1 |   3974 |  0         |
| sector_id_eia                                |    3974 |        1 |   3974 |  0         |
| sector_name_eia                              |    3974 |        1 |   3974 |  0         |
| service_area                                 |    3974 |        1 |   3974 |  0         |
| transmission_distribution_owner_id           |    3974 |        1 |   3974 |  0         |
| transmission_distribution_owner_name         |    3974 |        1 |   3974 |  0         |
| transmission_distribution_owner_state        |    3974 |        1 |   3974 |  0         |
| utility_id_eia                               |    3974 |        1 |   3974 |  0         |
| water_source                                 |    3974 |        1 |   3974 |  0         |
| data_maturity                                |    3974 |        1 |   3974 |  0         |
| plant_id_pudl                                |    3974 |        1 |   3974 |  0         |
| utility_name_eia                             |    3974 |        1 |   3974 |  0         |
| utility_id_pudl                              |    3974 |        1 |   3974 |  0         |
| balancing_authority_code_eia_consistent_rate |    3974 |        1 |   3974 |  0         |

**Pull request merged**
