### PR TITLE
If docs build interrupted, don't commit leftover autoapi files

### LINKED ISSUE #3825: When docs build is interrupted, ensure autoapi files aren't captured in git
When the docs build runs correctly, the `docs/autoapi/` folder is automatically removed. But, when this process is interrupted sometimes the folder remains behind. To avoid accidentally capturing these files in git, let's add them explicitly to `.gitignore`

### PR DESCRIPTION
**Pull request by e-belfer**
# Overview

Closes #3825.

What did you change?
Added `docs/autoapi` folder to ignore.

# Testing

How did you make sure this worked? How can a reviewer verify this?
Start building your docs, and interrupt them when you see the `autoapi` folder. Then, run `git status` - the files shouldn't appear as changed.

```[tasklist]
# To-do list
- [x] Review the PR yourself and call out any questions or issues you have
```

### CODE REVIEW

**Review by jdangerx — APPROVED** [review]
You know, I've deleted these files with `git clean -fd` a million times but never thought to just shove them into `.gitignore`. LGTM!

**Comment by e-belfer** [comment]
Waiting on #3823 to merge, which contains fixes to our integration tests that will prevent this PR from successfully merging.

**Comment by jdangerx** [comment]
Do you think that merge queue would do the right thing if we clicked the buttons in the right order?

**Comment by e-belfer** [comment]
> Do you think that merge queue would do the right thing if we clicked the buttons in the right order?

It would, but looks like Zane is still testing/implementing some fixes over in that branch!

**Comment by zaneselvans** [comment]
Sorry that other PR/CI debugging was harder than expected. I've got another tiny fix in #3827 for the CodeCov uploads which the fixes in #3823 inadvertently broke.

**Pull request merged**
