### PR TITLE
Increase datasette cloud run memory from 4GB to 32GB

### PR DESCRIPTION
**Pull request by bendnorman**
# PR Overview
The datasette deployment was manually upgraded to use 32 GB of memory but was not changed in the deployment script so it went back to using 4GB of memory. This resulted in our datasette deployment having stale data.

# PR Checklist

- [ ] Merge the most recent version of the branch you are merging into (probably `dev`).
- [ ] All CI checks are passing. [Run tests locally to debug failures](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#running-tests-with-tox)
- [ ] Make sure you've included good docstrings.
- [ ] For major data coverage & analysis changes, [run data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation)
- [ ] Include unit tests for new functions and classes.
- [ ] Defensive data quality/sanity checks in analyses & data processing functions.
- [ ] Update the [release notes](https://catalystcoop-pudl.readthedocs.io/en/latest/release_notes.html) and reference reference the PR and related issues.
- [ ] Do your own explanatory review of the PR to help the reviewer understand what's going on and identify issues preemptively.

### CODE REVIEW

**Review by zaneselvans — APPROVED** [review]
Were you able to manually redeploy Datasette using the command in the script (to get it up and running with the 2022 FERC data today)?

**Comment by bendnorman** [comment]
I redeployed datasette by updating the memory in the GCP UI.

**Comment by zaneselvans** [comment]
I wonder if it would be easy to set up the Datasette deployment as a separate GHA that pulls the published data from AWS.

**Comment by bendnorman** [comment]
I like that idea though we'd have to downloads dozens of GBs to the github runner when the data is already in nightly build VM.

**Pull request merged**
