### PR TITLE
Add EPA CEMS 2024Q1 

### PR DESCRIPTION
**Pull request by cmgosnell**
# Overview

Closes [#3620](https://github.com/catalyst-cooperative/pudl/issues/3620).

What problem does this address?
- this added a new few months of cems data

What did you change?
- i didn't have to change the full settings (bc "all") and i didn't change to fast settings bc the fast settings needs eia full year and cems quarter overlap. which is a note that when we update 860 fast year to be 2023 we will also need to update fast cems quarter.
- the transforms just worked np with the new data so nothing to see there.
- the only cems related validation test i could find was the crosswalk which i believe is not really connected to cems but i ran it locally regardless (i'm currently running the validation tests in the background)

# Testing

How did you make sure this worked? How can a reviewer verify this?

```[tasklist]
# To-do list
- [ ] If updating analyses or data processing functions: make sure to update or write data validation tests (e.g.,  `test_minmax_rows()`)
- [x] Update the [release notes](../docs/release_notes.rst): reference the PR and related issues.
- [x] Ensure docs build, unit & integration tests, and test coverage pass locally with `make pytest-coverage` (otherwise the merge queue may reject your PR)
- [x] Review the PR yourself and call out any questions or issues you have
- [ ] For minor ETL changes or data additions, once `make pytest-coverage` passes, make sure you have a fresh full PUDL DB downloaded locally, materialize new/changed assets and all their downstream assets and [run relevant data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation) using `pytest` and `--live-dbs`.
- [ ] For significant ETL, data coverage or analysis changes, once `make pytest-coverage` passes, ensure the full ETL runs locally and [run data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation) using `make pytest-validate` (a ~10 hour run). If you can't run this locally, run the `build-deploy-pudl` GitHub Action (or ask someone with permissions to). Then, check the logs on the `#pudl-deployments` Slack channel or `gs://builds.catalyst.coop`.
```

### CODE REVIEW

**Review by aesharpe — APPROVED** [review]
It's wild that we don't have any CEMS tests really

**Comment by zaneselvans** [comment]
In the past we've often (usually?) needed to add a few new plants to the CSV that defines the timezones for plants that don't yet show up in the EIA860 data. I'm a little surprised that that wasn't necessary. And you ran the few assets that are downstream of CEMS too?

**Comment by cmgosnell** [comment]
@zaneselvans the adding to the timezone csv has been less and less necessary over the years because we have more and more up to date eia data. I am running the full etl + validations now but i did run all the downstream assets

**Review by zaneselvans — APPROVED** [review]
Great! Glad it didn't put up a fight.  I was able to run all the assets up and downstream of the EPA CEMS assets and inspected the 2024 data and it looked sane.

**Pull request merged**
