### PR TITLE
Add DataSource Metadata for EPA-EIA Crosswalk

### PR DESCRIPTION
**Pull request by aesharpe**
## Overview of Changes:

These changes to the pudl metadata are intended to accommodate the archiving of the EPA-EIA Crosswalk. They pair with the changes in the `epa-eia-crosswalk` branch of the `pudl-zenodo-archive` repo

So far changes include:
- Adding and `epa_eia_crosswalk` key/value pair to the `SOURCES` dict in the `metadata/sources.py` module.
- Updating the `CONTRIBUTORS` dict in the `metadata/constants.py` module to reflect Zenodo requirements.
- Updating the `Contributor` class definition in `metadata/classes.py` to reflect changes in Zenodo requirements.

Once everything else is cleared up, I'm going to make the name `epa_eia_crosswalk` more specific here and in the zenodo/scraper repos

### CODE REVIEW

**Comment by aesharpe** [comment]
I was prompted to make these changes to the contributors dict when I got this kind of error when trying to run `zenodo_store epa_eia_crosswalk --sandbox --initialize`:

```
{'status': 400, 'message': 'Validation error.', 'errors': [{'field': 'metadata.creators.0.role', 'message': 'Unknown field name.'}, {'field': 'metadata.creators.1.role', 'message': 'Unknown field name.'}]}
```

This is referring to the "role" field in the contributor dict, defined in the `Contributor` class (I commented out all the ones that I got the above error for):

```
    name: String
    # path: HttpUrl = None
    # email: Email = None
    # role: Literal[
    #     "author", "contributor", "maintainer", "publisher", "wrangler"
    # ] = "contributor"
    affiliation: String = None
    # orcid: String = None
```

Now, the values in the `CONTRIBUTORS` dict in `constants.py` look like this:

```
    "zane-selvans": {
        "name": "Zane Selvans",
        # "email": "zane.selvans@catalyst.coop",
        # "path": "https://amateurearthling.org",
        # "role": "wrangler",
        "affiliation": "Catalyst Cooperative",
        # "orcid": "0000-0002-9961-7208",
```

I checked out the [Zenodo Developer](https://developers.zenodo.org/#representation) website and saw this to back up these changes:
Screen Shot 2022-06-06 at 3 00 45 PM

Now when I run `zenodo_store epa_eia_crosswalk --sandbox --initialize` the data are successfully uploaded to zenodo, but I get the following error in my terminal: 

```
Found the following 1 datapackage validation errors:
  * Descriptor validation error: 'title' is a required property at "contributors/0" in descriptor and at "properties/contributors/items/required" in profile
Traceback (most recent call last):
  File "/Users/aesharpe/mambaforge/envs/pudl-zenodo-storage/bin/zenodo_store", line 33, in <module>
    sys.exit(load_entry_point('pudl-zenodo-storage', 'console_scripts', 'zenodo_store')())
  File "/Users/aesharpe/Desktop/Work/Catalyst_Coop/Repos/pudl-zenodo-storage/src/pudl_zenodo_storage/cli.py", line 483, in main
    result = initial_run(
  File "/Users/aesharpe/Desktop/Work/Catalyst_Coop/Repos/pudl-zenodo-storage/src/pudl_zenodo_storage/cli.py", line 283, in initial_run
    new_datapackage(zenodo, datapackager, deposition)
  File "/Users/aesharpe/Desktop/Work/Catalyst_Coop/Repos/pudl-zenodo-storage/src/pudl_zenodo_storage/cli.py", line 129, in new_datapackage
    raise datapkg.errors[0]
datapackage.exceptions.ValidationError: Descriptor validation error: 'title' is a required property at "contributors/0" in descriptor and at "properties/contributors/items/required" in profile
```

It seems like there is a discrepancy between what the datapackage requires and what Zenodo requires. Can anyone help me clear this up?

**Comment by aesharpe** [comment]
RE: new contributor data to accommodate Zenodo changes---
I'm not sure whether I should make these changes directly in the Dict or in a function that could alter the dict for Zenodo's purposes (in case the contributor data gets used elsewhere in a different format).

**Comment by zaneselvans** [comment]
There are two completely separate sets of requirements, for two completely separate sets of metadata. Each Zenodo deposition has a set of metadata associated with it, and the structure / allowable values are defined by Zenodo.

Data Packages have nothing to do with Zenodo's metadata, except that we use some of the Data Package metadata to figure out what values we should fill in for some of the Zenodo metadata fields.  E.g. [here's the specification for a Data Package contributor](https://specs.frictionlessdata.io/data-package/#contributors).

It seems like these two metadata structures and their requirements are getting confused in here.

IIRC, **only** data package metadata should be getting stored in the `DataSource` and other PUDL metadata classes.  Some of those values are then used to dynamically populate the Zenodo metadata fields when the new deposition is created.

At the same time, metadata which only pertains to the Zenodo archives and doesn't show up or have a direct analog in the Data Packages is stored or defined in the `pudl-zenodo-storage` repository and the metadata structures there.

**Comment by zaneselvans** [comment]
None of the `contributor` metadata structures should be changed on the PUDL side -- they need to continue to conform to [the Data Package standards](https://specs.frictionlessdata.io/data-package/#metadata) (as the docstrings both in PUDL and the Zenodo archiver repo indicate).

As it is, the contributors that show up in the `datapackage.json` (which is derived from `pudl_zenodo_storage.frictionless.core.Datapackage.contributors` for the Zenodo archive will be invalid. I'm not sure if there are other places where they show up, but they're currently expected to conform to the data package standard.

If Zenodo has more stringent and also different requirements for the contents of the analogous contributor fields, then that translation from the data package notion of contributors to the Zenodo notion of contributors needs to happen in the `pudl-zenodo-storage` code.

Right now all it does is create a list of the dictionary representations of the data package version of the contributors, in `_generate_metadata()`:

```py
    return {
        "title": f"PUDL Raw {data_source.title}",
        "language": "eng",
        "upload_type": "dataset",
        "description": f"<p>{data_source.description} Archived from\n"
        f'<a href="{data_source.path}">{data_source.path}</a></p>'
        f"{pudl_description}",
        "creators": [contributor.dict() for contributor in data_source.contributors],
        "access_right": "open",
        "license": data_source.license_raw.name,
        "keywords": [*data_source.keywords, data_source_uuid],
    }
```

So you might add a helper function in this module that translates a data package contributor dictionary into a zenodo contributor dictionary.  Or alternatively you could add a `contributor.zenodo_dict()` method to the Pydantic model in PUDL and then use that instead of `contributor.dict()` in the list comprehension.

**Comment by aesharpe** [comment]
> So you might add a helper function in this module that translates a data package contributor dictionary into a zenodo contributor dictionary.

This was the route that I took with these new commits!

**Review by zaneselvans — APPROVED** [review]
Looks good. I'm going to go ahead and merge this so that I can get the `pudl-zenodo-storage` PR tests to pass while referring to `dev` as they do by default.

**Pull request merged**
